### ISSUE TITLE
item-after not aligned correctly?

### ISSUE THREAD

**Issue by KuenzelIT** [framework7io/framework7#1007]
This is a:
- [x] bug
- [ ] enhancement
- [ ] feature-discussion (RFC)
- Framework7 Version: 1.4.2
- Platform and Target: Android for now
### What you did

I'm using a list-block like this:

```
<div class="list-block">
      <ul>
         <li>
            <div class="item-content">
                  <div class="item-inner">
                        <div class="item-title">
                             Name
                         </div>
                         <div class="item-after">
                            <b>Test</b>
                         </div>
                  </div>
            </div>                         
        </li>
    </ul>
</div>
```
### Expected Behavior

I kind of expect, that the content in "item-after" is aligned to the right or at least aligned to the left with a "virtual" vertical line. Just clean below each other.
### Actual Behavior

The list-items are not aligned. Some are aligned to the right (if the title is longer), others are somewhere in the middle, but not centered.

This may be the intention, but it looks strange and not correct for me. So is this correct?

Thanks for the Framework btw, it has a lot of nice and easy to use features!

**Comment by alexmyczko** [comment]
Do you have it online? I also have this problem with 1.5.0 but only with the browsers Firefox and Internet Explorer... here for you to try: http://www.aiei.ch/airports/

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
