### ISSUE TITLE
browser refresh

### ISSUE THREAD

**Issue by gkcoe** [framework7io/framework7#1008]
the demo kitchen-sink-iso i set pushState:true in kitchen-sink.js

Index -> Navbars And Toolbars-> Deep Navbar.

on Deep Navbar page click browser refresh, then can't click browser back to Index.

**Comment by gkcoe** [comment]
can anyone tell me why? thanks..

**Comment by ZanderBrown** [comment]
Does this still happen? Is anything shown in the console?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
