### ISSUE TITLE
Swipeable tab: list view accordion is not displaying properly

### ISSUE THREAD

**Issue by Rinkuk1993** [framework7io/framework7#1028]
This is a (multiple allowed):
- [x] bug
- [x] enhancement
- [ ] feature-discussion (RFC)
- Framework7 Version: Framework7 v1.4.2 - Updated on February 27, 2016
- Platform and Target: CORDOVA, IOS.
### What you did

There are 2 tabs ([swipeable](http://framework7.io/docs/tabs.html#swipeable-tabs)). Both Tab1 (containing simple text) and Tab2 (containing accordion list) are seperate view which is rendered once that view's tab gets active. 
There are 2 ways to go to Tab2  : 1) On click, 2) On swipe
On click, everything works perfectly fine but on swipe the accordion list of Tab2 is displayed half (which occurs randomly)
### Expected Behavior

On tab swipe, the accordion shall be displayed properly i.e. all "item-title" of list needs to be displayed. 
### Actual Behavior

1) On tab swipe, Randomly some "item-title" will be missing, which will be displayed only if clicked on one of the accordion item. Sometimes it comes properly but if continuously swiped to and fro, the above issue can be seen.
2) On Tab2 click, everything is rendered properly.

NOTE : Same code has been used for android (CORDOVA) and it works perfectly fine.

Please help me  to fix this issue as soon as possible.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
