### ISSUE TITLE
Ripple effect not disapire

### ISSUE THREAD

**Issue by simeonov** [framework7io/framework7#1039]
I have issue on ripple effect links. When i click on link ripple effects is show but not hide after animation.
Here is video wich shows problem: 
https://youtu.be/77JcjbwLXRg

I use last version of framework.

**Comment by proudUzbek** [comment]
same problem.﻿

**Comment by ZanderBrown** [comment]
use polymer or mdl. the F7 Material theme is appalling. It incorrectly follows the material spec & is buggy

**Comment by GuillaumeBiton** [comment]
Hi, I think you must have an issue in your code. take a look at this [demo on jsbin](https://jsbin.com/gaqopex/edit?html,output)

**Comment by proudUzbek** [comment]
In my case it works fine in my browser but after building it I get this problem

**Comment by ZanderBrown** [comment]
Could you please share a CodePen or jsFiddle so we can reproduce this?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
