### ISSUE TITLE
Swiper Slider conflicts with the Framework7 preloader

### ISSUE THREAD

**Issue by dumconstantin** [framework7io/framework7#1062]
This is a (multiple allowed):
- [x] bug
- [ ] enhancement
- [ ] feature-discussion (RFC)
- Framework7 Version: 1.4.2
- Platform and Target: Chrome
### What you did

Was using the [Swiper Slider from Framwork7 ](http://framework7.io/docs/swiper.html) and inside a child element I added an element with class="preloader".
### Expected Behavior

The **.preloader** class should have been the default Framework7 preloader.
### Actual Behavior

The **.preloader** class was overwritten by Swiper Slider and had a very different effect.

Both Swiper Slider and Framework7 use the same class for the Preloader - there should be a way to be able to use both preloaders in the Swiper Slider context.

**Comment by lezhizhe** [comment]
I have this problem too

**Comment by valnub** [comment]
I don't think this is a bug but more a feature request

**Comment by dumconstantin** [comment]
Well, [Framework7 comes with powerful and most modern touch slider ever - Swiper Slider ](http://framework7.io/docs/swiper.html) which makes this a bug as there are conflicting components in the standard build of F7...

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
