### ISSUE TITLE
feature-discussion:router.remove() , view.remove()

### ISSUE THREAD

**Issue by evolutionjay** [framework7io/framework7#1073]
This is a (multiple allowed):
- [ ] bug
- [ ] enhancement
- [x] feature-discussion (RFC)
- Framework7 Version: 1.4.2.
- Platform and Target:ALL
### What you did

Demand product development process product.
### Expected Behavior

Hoping to remove the specified `page` and rearrange `pushState`
e.g

``` javascript
myApp.mainView.router.remove(options)
```

We want to increase the removal of `view` API
e.g

``` javascript
myApp.otherView.remove()
```

**Comment by evolutionjay** [comment]
when the view is removed, the pages in view also trigger remove event

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
