### ISSUE TITLE
Morph To Popover Problem

### ISSUE THREAD

**Issue by mustafakucuk** [framework7io/framework7#1088]
Hi, **Framework7 Morph To Popover** Problem

![ekran resmi 2016-08-07 20 49 24](https://cloud.githubusercontent.com/assets/7347594/17464163/75834a9c-5ce0-11e6-842c-262e8fb6e194.png)

How can I solve?

Thanks

**Comment by J05HI** [comment]
I'm getting the same bug on Chrome on Android.
I'll fix that and make a pull request.

**Comment by J05HI** [comment]
Fixed and working!

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue

**Comment by J05HI** [comment]
@nolimits4web
Latest version works perfectly fine!
