### ISSUE TITLE
what‘s ths use of class “inputs-list”？

### ISSUE THREAD

**Issue by imac8t** [framework7io/framework7#1178]
what‘s ths use of class “inputs-list”？

**Comment by imac8t** [comment]
i have to remove it because of layout.it will be heve any problem?

**Comment by ZanderBrown** [comment]
Could you please provide some more detail? Some code?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
