### ISSUE TITLE
 I do not want  Some pages appear in router.back()

### ISSUE THREAD

**Issue by lixinchuang** [framework7io/framework7#1185]
usually,some page is not usefull, but it alwasy appear when  click back icon,  how can I hide it forever?

**Comment by ZanderBrown** [comment]
It's not pretty but you could use `router.back(); router.back();`
But it's normal for all pages to appear in history.

Maybe you need to rethink your app hierarchy

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
