### ISSUE TITLE
Little scroll bug

### ISSUE THREAD

**Issue by quic5** [framework7io/framework7#1220]
In the standalone web app on ios you can scroll in alerts and see the ugly grey

**Comment by JosephShenton** [comment]
Check my issue, if they don't add it to f7 just manually add iNoBounce that fixes it

**Comment by ZanderBrown** [comment]
Of course it's helpful to say what issue you mean  (#1229)

**Comment by JosephShenton** [comment]
Sorry, i was on my phone and was half asleep.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
