### ISSUE TITLE
is there any plans of developing material design search pattern?

### ISSUE THREAD

**Issue by boynet** [framework7io/framework7#1235]
* [] bug
* [x ] enhancement
* [x ] feature-discussion (RFC)

is there any plans of developing  [material design search pattern](https://material.google.com/patterns/search.html#search-in-app-search
)?

I think we need the two types

- Persistent search
- Expandable search

If not plans I can create a plugin for that

**Comment by nolimits4web** [comment]
Not at the moment. Would be great to see plugin from you ;)

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
