### ISSUE TITLE
Swipeable tabs does not work with hideNavbarOnPageScroll

### ISSUE THREAD

**Issue by DavidGOrtega** [framework7io/framework7#1241]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.5.0
* Platform and Target: ANDROID, CHROME

### Expected Behavior
NavBar should hide/appear for each tab

### Actual Behavior
First tab works the rest are locked

The code is looking just only to scrollContent[0]

**Comment by ZanderBrown** [comment]
Have you code a codepen / jsfiddle handy?

**Comment by stkook** [comment]
Here is code. (Tab 2 show/hide navbar wrong)

http://codepen.io/anon/pen/wJqwWg

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
