### ISSUE TITLE
Photo Browser's images sometimes disappears partly or fully in F7 1.5.0+

### ISSUE THREAD

**Issue by applecat** [framework7io/framework7#1253]
This is a:
* [x] bug

* Framework7 Versions: 1.5.0, 1.5.2 (in 1.4.2 everything in ok)
* Platform and Target: CORDOVA + IOS (iPhone 5s + iPhone 6 tested) + Safari browser on Mac.
In Google Chrome browser all works fine.
* Live Link or JSFiddle/Codepen:
F7==1.5.2 — https://jsfiddle.net/4mejdojk/2/ (images disappears sometimes after slide change)
F7==1.4.2 — https://jsfiddle.net/mvs820k0/3/ (all works fine)

### What you did
Photo Browser run like this:
```
var images = [...];
var newPhotoBrowser = myApp.photoBrowser({
    photos: images,
    theme: 'dark'
});
newPhotoBrowser.open();
```

Here is how it looks in browser and in iPhone emulator when image disappears:
[browser1](http://apple-cat.ru/photobrowser/bug1.png), [browser2](http://apple-cat.ru/photobrowser/bug2.png), [browser3](http://apple-cat.ru/photobrowser/bug3.png), [emulator1](http://apple-cat.ru/photobrowser/bug4.png), [emulator2](http://apple-cat.ru/photobrowser/bug5.png)

And when image redrawing (for example, for zooming or when swipe-to-close action, or with browser resize) — image displays full again.

**Comment by jimisens** [comment]
Hello!
I have exactly the same problem. Any Ideas ? 
Thanks

**Comment by valnub** [comment]
Hi, I tested on Safari for Mac on https://jsfiddle.net/4mejdojk/2/ and it works fine for me. Are you sure that the problem still exists?

**Comment by applecat** [comment]
Yes, the problem still exists on https://jsfiddle.net/4mejdojk/2/ (tested in Safari 10.0.2 on Mac). To see how images partly disappears you need click next/prev buttons fast. Here is [video example](http://apple-cat.ru/photobrowser/example.mp4)

**Comment by valnub** [comment]
Sorry, I still cannot reproduce the issue on Safari 10.0.2

**Comment by oudoken** [comment]
Hi there,
I can confirm also the problem. If lazyLoading is enabled the image are loaded and visible correctly when tapping the NEXT image (or sliding right) if sliding back the problem is here again (no lazy because the image it's already there).
Also double tap or pinch/punch make the full image visible.
Some sort of visual glitch...

**Comment by seme1** [comment]
I can confirm that I witnessed this bug occurring from time to time. 

This is another related bug I'm also suffering from. 
https://github.com/nolimits4web/Framework7/issues/1427

**Comment by ZanderBrown** [comment]
No matter what i do i simply can't reproduce this.

@nolimits4web, @macdonst you had any luck reproducing this?

**Comment by jimisens** [comment]
I confirm having the same problem on IOS. Android works fine. 
I just update framework7 yesterday to the last version 1.5.4 but the problem still there. 
My partial solution is : 
- Disable zoom effect
- Apply some CSS rules to the images tag 

SASS : 
.swiper-slide-active > span.swiper-zoom-container{
  transform: translate3d(0px, 0px, 0px) !important;
  img{
    transform: translate3d(0px, 0px, 0px) !important;
  }
}

**Comment by seme1** [comment]
Any updates on this bug ? This is related to a previous issue I reported https://github.com/nolimits4web/Framework7/issues/1427
both bugs are extremely annoying when they appear. I noticed that the partial image appearances occurs when first viewing the images with the auto slider. After first view, re-opening the slider with the same images cause them to appear fully as expected. However, this bug is making my app extremely annoying.

**Comment by smshuja** [comment]
@jimisens This works for me with zoom.

```
.swiper-slide-active > span.swiper-zoom-container{
  transform: rotateX(0deg);
  img{
    transform: rotateX(0deg);
  }
}
```

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
