### ISSUE TITLE
Tab bar size problem

### ISSUE THREAD

**Issue by Abhinavsinghpravartan** [framework7io/framework7#1294]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: EXACT RELEASE VERSION OR COMMIT HASH, HERE.
* Platform and Target: CORDOVA, ANDROID, ETC.

### What you did
i am trying to use tabs but toolbar-inner is not working when call multiple tab tageg in index.
I will explain in briefly:-
Steps:-
1. I have created index.html
2. create new page with tabs  items.html
3. create another page with tabs favorite-items.html
4 Navigation:- index to items.html(tabs working fine) then items.html to favorite-items.html (tab not working properly if swipe the tab)

### Expected Behavior
table bottom line in same way as first time click

### Actual Behavior
table bottom line in size problem when swipe on second
![capture](https://cloud.githubusercontent.com/assets/25173431/22018726/4df9f5cc-dcd6-11e6-880a-760e91a2ff8d.PNG)
![capture](https://cloud.githubusercontent.com/assets/25173431/22018756/7c6f6d92-dcd6-11e6-8358-6acac7d65da8.PNG)

**Comment by nolimits4web** [comment]
It is hard to say like that. Would be really good to see somekind of live example or JSfiddle/Codepen with the issue

**Comment by evandrojr** [comment]
Open this link on iphone or Chrome PC  version >= 56. FF works fine.

http://bomlugarclubedasartes.com/app/

Notice that the tab does not fit the screen causing a second scrollbar to appear. Seems to me it was caused by some webkit update. It did used to work, I checked with older versions of my app and all are having the same bug.

I will post a fix if I manage to fix it.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
