### ISSUE TITLE
cordova plugin compatibilty

### ISSUE THREAD

**Issue by bigbossmaher** [framework7io/framework7#1297]
realy i have one issue
i'm making an hybrid app with framework7.
i implemeted the the cordova-plugin-goolemaps , because the google maps javascript api have not some gesture controls like rotation by two fingers.
the problem is that every thing on the map ( text box or panel side bars ) will not working ( the clics are captured by the map ).
i opened an issue post on the github of the plugin , the developper suggest to move the div of the map directly under the div as solution ( it works )
but you know that i should respect the framework7 layout
this is the question link
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1268

**Comment by centrual** [comment]
We talked about this problem in: http://forum.framework7.io/#!/questions:cordova-google-maps-plugin

**Comment by bigbossmaher** [comment]
@centrual , as i see the problem is not solved yet

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
