### ISSUE TITLE
Photo Browser on Android: Pinch zoom is okay when zooming in, but there is a problem when zooming out

### ISSUE THREAD

**Issue by EmreErdogan** [framework7io/framework7#1332]
* Framework7 Version: 1.5.2
* Platform and Target: Cordova Android
* Live Link: I tested the behaviour on Android 5.0.2 on a Cordova application. I cannot provide an APK right now, but the problem can also be seen on the following demo page: https://framework7.io/docs-demos/photo-browser.html

Please open the link with an Android device and click "Standalone" under light theme section. Pinch zoom an image, then release your fingers off the screen, then finally try to resize the image back to its original size. You will end up with an image lying in an unwanted position of the screen with an unwanted size.

An example screenshot from an app running on my device is below. The image shows the situation after zooming out.

![screenshot_2017-02-02-18-38-14](https://cloud.githubusercontent.com/assets/2360385/22556475/efe34a1e-e96f-11e6-8acf-2dc7f532a7e7.png)

**Comment by EmreErdogan** [comment]
Is there any way to hack Framework7 1.5.2 to disable pinch-to-zoom feature only for android?

**Comment by media0101** [comment]
This problem has not yet been solved on Android (Chrome)?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
