### ISSUE TITLE
preproсess bug

### ISSUE THREAD

**Issue by login2030** [framework7io/framework7#1334]
* [x] bug
* Framework7 Version: 1.5.2
* Platform and Target: Browser
* [Simple app link](http://login2030.tmweb.ru/F7-preprocessBug/)
* [js file](http://login2030.tmweb.ru/F7-preprocessBug/app.js)

### What you did
To download page I used preproсess method. Since pages use Ajax to get the data.
Pages will open in a sequence **index.html -> ip.html ->ip2.html**

### Expected Behavior
I expect that during the transition **ip2.html -> ip.html -> index.html** the application will not freeze on the page ip.html

### Actual Behavior
In the above scheme reverse motion the application freezes on the page ip.html

**Comment by valnub** [comment]
Your back button targets to `#`, thus history gets lost.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
