### ISSUE TITLE
Switch Component Too Hard to Toggle on Material Theme and Android Mobile

### ISSUE THREAD

**Issue by centrual** [framework7io/framework7#1336]
This is an:
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.5.2
* Platform and Target: ANDROID - Material Theme

### What you did
I added switch component to my app.

### Expected Behavior
Easily switch between false and true state.

### Actual Behavior
It's easy for desktop browsers but too hard for mobile touch on Android phones.

**Comment by ZanderBrown** [comment]
Could you expand?

**Comment by kaiyes** [comment]
Facing the same thing in IOS too. Double tapping the switch works though. could be this though 
https://css-tricks.com/annoying-mobile-double-tap-link-issue/

**Comment by centrual** [comment]
@ZanderBrown
1) Create new cordova project
2) Add framework7 to component
3) Change theme to material
4) Add some switch input components to page
5) Run in your phone
6) Try to change inputs

It is very difficult to open and close the switch. So we need to change effective tap area.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue

**Comment by hillgr** [comment]
Downloaded newest version today and still seems to be an issue.

**Comment by hillgr** [comment]
Upon further investigation, it seems only to be a problem when a checkbox toggle is nested inside of a listview. Maybe there is some sort of click handler that is forcing a double tap to trigger the toggle
