### ISSUE TITLE
App Freeze caused by opening/closing panel

### ISSUE THREAD

**Issue by dawuwu** [framework7io/framework7#1402]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.5.3
* Platform and Target: Android, Crodova

### What you did
1. Pressing the Navbar Icon to open the left/right panel.
2. Touching the Panel before transition ends
3. Closing the panel again by Navbar Icon

To force the bug, as example you can use this App:
https://play.google.com/store/apps/details?id=com.mobilecrazies.fractureclassification.android&hl=en
(this is not my app, I looked in the showcase for a suitable app for this bug)

Rapidly press Menuicon top right and somewhere on the Navbar top left. After a few seconds the Menuicon will stay highlighted and the app freezes

Screenshot:
![screenshot_20170309-101424](https://cloud.githubusercontent.com/assets/12020928/23743820/6016323a-04b2-11e7-88d5-efd2954d355a.png)

In my app I have the Menuicon top left, in this scenario the bug appears very often while normal using the app (not forcing it with rapidly touch spam).

**Comment by StefansArya** [comment]
Same with me, but the app was little slow and not freezed in my devices. It because the Cordova in Android doesn't support hardware acceleration (Depend on your android version), that's why some visual effect will make your app slower.
To solve this, I'm installed **crosswalk plugin** and let my application have hardware acceleration. But the size is costly..

**Comment by dawuwu** [comment]
I experienced that bug on all android versions (4 - 7) with and without crosswalk.

**Comment by StefansArya** [comment]
It doesn't freeze in Mito A18, but the ripple effect was not removed when the panel closed immediately

**Comment by centrual** [comment]
It's about `passiveListener` and `preventDefault`. Wait for weekend for update.

**Comment by dawuwu** [comment]
@centrual,
any update on this issue?

**Comment by centrual** [comment]
@dawuwu Currently not, update is soon, it will fix on next release.

**Comment by dawuwu** [comment]
@centrual 
the bug still occurs with 1.5.4

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue

**Comment by ptkdev** [comment]
:+1:
