### ISSUE TITLE
input on blur even will run two times

### ISSUE THREAD

**Issue by yoke1990** [framework7io/framework7#1406]
**HTML**:
```html
<input name="mobile" type="text" id="mobile">
```
**JavaScript**:
```javascript
$$("mobile").on("blur",function(e){
     if（moblile）{consolo.log("have mobile")}
     else{consolo.log("no mobile")}
});
```
when i input some number.then i see
```
have mobile
have mobile
```
two times

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
