### ISSUE TITLE
Framework7-1.5.3 - Back issue

### ISSUE THREAD

**Issue by murliatdure** [framework7io/framework7#1407]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: Framework7-1.5.3
* Platform and Target: Cordova & Web

### What you did
Back link feature of the existing app got disturbed, it goes to index.html

### Expected Behavior
Last history stack should popout

### Actual Behavior
Goes to index.html

**Comment by ZanderBrown** [comment]
Can you provide some code please?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
