### ISSUE TITLE
Restore old iOS Notifications theme

### ISSUE THREAD

**Issue by tinyCoder32** [framework7io/framework7#1420]
Hi, I guess that since 1.5.0 the iOS notifications style has been updated to iOS 10 style, I'm wondering how can I restore the previous style of the notifications (only) in the best way.

Thank you.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
