### ISSUE TITLE
Admob ad closes popup when dismissed, on Android not iOS

### ISSUE THREAD

**Issue by peterel** [framework7io/framework7#1426]
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.5.0 
* Platform and Target: Android (HTC One)

### What you did
This works on iOS. I open an ad with cordova admob plugin and therafter a (dynamic) popup (which then opens in the background of the ad). When the user closes the ad, the popup is there waiting for them. But on Android device the closing of the ad also closes the popup. Code:
```
if (typeof AdMob !== 'undefined') {
    if(AdMob) AdMob.showInterstitial();
    }
popup(data, to, popup);
```
### Expected Behavior
I expect the popup to stay open in spite of the ad being closed (as in iOS).

### Actual Behavior
The popup closes, not on iOS but on Android device, when the ad is closed.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
