### ISSUE TITLE
smart-select non duplicate items selection problem

### ISSUE THREAD

**Issue by kiralikbeyin** [framework7io/framework7#1428]
This is a (multiple allowed):
* [x] bug 

### What you did

````
<script id="turtemp" type="text/template7">
        <a href="#" class="item-link smart-select">
            <div class="item-input" data-context-name="tur">
                <select name="tursec" id="cihazturu">
                                          {{#each tur}}
                                                {{#if this}}
                                          <option value={{this}}>{{this}}</option>
                                                {{else}}{{/if}}
                                           {{/each}}
                                    </select>
                <div class="item-content">
                    <div class="item-inner">
                        <div class="item-title">Tür Seç</div>
                    </div>
                </div>
            </div>
        </a>
    </script>
````

### Expected Behavior
 When you select an item and return to back page you must see selected item

### Actual Behavior
 Example:
1.item : High value
2.item : High i am second item
x.item : Hi eben

If i select 2. item it will return 1. item "High value" because they are beginning with the same word "High"

**Comment by centrual** [comment]
Jsfiddle aracılığıyla bir önizleme hazırlayabilir misin?
Can you make demo in jsfiddle?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
