### ISSUE TITLE
When I build an apk file using cordova, the apk file shows blank screen on device

### ISSUE THREAD

**Issue by alapanme** [framework7io/framework7#1431]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

I have created a project on simple Framework+VueJS template (Framework7 Vue Webpack App Template). I build an apk file using cordova. Now when I am installing and running the android file on the device, I am getting an blank screen.

**Comment by macdonst** [comment]
@alapanme not near enough information to start debugging. What do you see in console logs or Android logcat?

**Comment by alapanme** [comment]
When I debugged, it seems the the index.html file was not loading. 
What I did was, I created a Cordova project and inside the www folder I first copied all the F&+VueJS template html, js, css files and then installed the dependencies for Framework7+VueJS project using npm install.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
