### ISSUE TITLE
Slider problem when using flip effect with vertical direction

### ISSUE THREAD

**Issue by tinyCoder32** [framework7io/framework7#1451]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.5.4
* Platform and Target: Latest Firefox on Mac

### What you did
A simple swiper slider with this init code:

```
var mySwiper = new Swiper('.swiper-container', {
    preloadImages: false,
    lazyLoading: true,
    pagination: '.swiper-pagination',
    direction: 'vertical',
    effect: 'flip'
	});
```

### Expected Behavior
The slide to flip in its same place.

### Actual Behavior
The slide is flipping up outside the screen.

### Sample Video
![untitled](https://cloud.githubusercontent.com/assets/17817239/24353000/70b41d46-12f4-11e7-8cb4-12d0402c3af3.gif)

**Comment by ZanderBrown** [comment]
The problem seems to be that the content is too tall

**Comment by tinyCoder32** [comment]
It is a 350x263 Image.

**Comment by ZanderBrown** [comment]
that's irrelevant how would Swiper know that that would put it off the top of the screen.

You should insure that your content will fit

**Comment by nolimits4web** [comment]
There is something wrong with the layout. Would be good to know how to replicate this issue or see the Fiddle with the issue or live example

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
