### ISSUE TITLE
Open SmartSelect from Modal?

### ISSUE THREAD

**Issue by tinyCoder32** [framework7io/framework7#1457]
Hi, I knew recently that opening SmartSelect inside a `popup` require a correct and initialized view layout, but what does it need to work inside a custom modal?

![screen shot 2017-03-30 at 1 13 36 am](https://cloud.githubusercontent.com/assets/17817239/24479054/21480774-14e6-11e7-9cbe-20f57997796d.png)

Is there a way to initialize the Smart Select manually after the modal is opened, maybe?

**Comment by nolimits4web** [comment]
Same requirement, put there View with pages/page and init it

**Comment by tinyCoder32** [comment]
I did tried that before posting, but then the modal turned empty.

**Comment by nolimits4web** [comment]
You may probably need to set fixed height size on this View inside of modal

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
