### ISSUE TITLE
Form-Elements in accordion-content have two separator-lines (css-after-content) beneath

### ISSUE THREAD

**Issue by cyberbeat** [framework7io/framework7#1460]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.4.2
* Platform and Target: Android
* Live Link or JSFiddle/Codepen: https://codepen.io/anon/pen/dvwJop

I think this css-code (from framework7 material-theme) is responsible for the bug:

```
.list-block li li:last-child .item-inner:after,
.list-block li:last-child li .item-inner:after {
  content: '';
  position: absolute;
  left: 0;
  bottom: 0;
  right: auto;
  top: auto;
  height: 1px;
  width: 100%;
  background-color: rgba(0, 0, 0, 0.12);
  display: block;
  z-index: 15;
  -webkit-transform-origin: 50% 100%;
  transform-origin: 50% 100%;
}
```

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
