### ISSUE TITLE
Form validation (for next releases)

### ISSUE THREAD

**Issue by vousys** [framework7io/framework7#1461]
Hi! I love your framework. Maybe you could add for the next realeases a "form validation", so we didn't need to use jquery for that. It would be very helpfully.
One more:
In input:password it would be fantastic to have the strong type of it. With the "ruler" :)

**Comment by J05HI** [comment]
Nice idea :)

**Comment by DareDevil73** [comment]
I need it too.

**Comment by robbash** [comment]
+1

**Comment by Mindex404** [comment]
+1

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
