### ISSUE TITLE
Changing color of range slider left hand side not working anymore

### ISSUE THREAD

**Issue by snakeman21** [framework7io/framework7#1463]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: EXACT RELEASE VERSION OR COMMIT HASH, HERE.
**1.5.4**
* Platform and Target: PLATFORM CLIENT YOU ARE TARGETING SUCH AS CORDOVA, IOS, 
ANDROID, ETC.
**iOS 10.3**

### What you did
EXPLAIN WHAT YOU DID, PREFERABLY WITH CODE EXAMPLES, HERE.

You used to be able to just do this `.range-slider input[type=range]::-webkit-slider-thumb:before`, but it doesn't work anymore. You can see for yourself that it doesn't work by going to the kitchen sink example of it on mobile Safari (if you have iOS 10.3). You can no longer see the blue color on the left.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
