### ISSUE TITLE
I want to remove '#' from url. when input 'http://localhost:8080/about/' in the browser, the page cann't direct to 'about'. 

### ISSUE THREAD

**Issue by leonyuxiaojie** [framework7io/framework7#1477]
var v = new Vue({
  el: '#app',
  template: '<app/>',
  framework7: {
    root: '#app',
    pushState: true,
    routes: Routes,
    pushStateSeparator : "",
    cacheIgnoreGetParameters: true,
    uniqueHistoryIgnoreGetParameters: true,
    uniqueHistory:true
  },
  // Register App Component
  components: {
    app: App
  }
});

我想把地址栏里面的“#”去掉， pushStateSeparator:"", 点击跳转是ok的，但是在地址栏上面访问http://localhost:8080/about/的话  页面报错“Failed to load resource: the server responded with a status of 404 (Not Found)”，是否需要设置nginx
类似于
location / {
  try_files $uri $uri/ /index.html;
}

**Comment by leonyuxiaojie** [comment]
Code:
var v = new Vue({
el: '#app',
template: '',
framework7: {
root: '#app',
pushState: true,
routes: Routes,
pushStateSeparator : "",
cacheIgnoreGetParameters: true,
uniqueHistoryIgnoreGetParameters: true,
uniqueHistory:true
},
// Register App Component
components: {
app: App
}
});
Nginx config:
location / {
try_files $uri $uri/ /index.html;
}
Now，I want to remove '#' from url. when input 'http://localhost:8080/about/' in the browser, the page cann't direct to 'about'. And the page show error: Failed to load resource: the server responded with a status of 404 (Not Found).

**Comment by ErroneousFatality** [comment]
This is not a bug. There is no way for a JS framework to fix this.
Once you enter a proper url into your browser it will take you to that route, which in your case is http://localhost:8080/about. 
Your server then tries to find the resource which is mapped to be returned on the 'about' path.
You can make this work if you set your server up so that every path returns the same resource, which is your framework7 application. 
I'm not sure if you'd then need to make framework7 parse the url so its can navigate to the proper page, or if it would do that automatically.

**Comment by ZanderBrown** [comment]
F7 can handle hashless push state but something needs to be done server side as @ErroneousFatality said

**Comment by peon501** [comment]
did something like that by removing ajax, and used url paths, it made a lot of problems, but i did it. some elements didnt worked well, but by changeing some stuff I came to result, with server loading, not from ajax :F.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
