### ISSUE TITLE
Framework7 route error

### ISSUE THREAD

**Issue by Leitonez** [framework7io/framework7#1480]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.4.2
* Platform and Target: IOS

### What you did
I am using Framework7 with Angular.js and everything works fine. But when I try to use ng-include in one of my pages, my app got broken. I realized that url becomes wrong.
Before I call the page which has ng-include, my route is:
app/view/index.html#!/menu.html (and it's OK)
After my page with ng-include load, I got the follow url:
app/view/index.html#/!/requestcategories.html (with a slash between #! – which seems wrong)

### Expected Behavior
I believe that route should be:
app/view/index.html#!/requestcategories.html
Even after ng-include performs the request.

### Actual Behavior
Url broken: app/view/index.html#/!/requestcategories.html

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
