### ISSUE TITLE
lazy load error when image in an animated tab

### ISSUE THREAD

**Issue by yexing** [framework7io/framework7#1481]
in lazy-load.js line 119

when image in an animated tab and the tab is not the first(and active) tab,  el.getBoundingClientRect() will get the rect out of the window(because the tab is out of the window when tab:show event is trigged). So I think we should get the tab's rect first.

This is an example but not the solution.

            function isElementInViewport (el) {
                var rect = el.getBoundingClientRect();
                // xingye 如果使用animated-tab，图片的位置会是整个tab相对于窗口的位置
                // 而此时tab可能在窗口之外
                var rectContent = pageContent[0].getBoundingClientRect()

                var threshold = app.params.imagesLazyLoadThreshold || 0;
                return (
                    rect.top >= (rectContent.top - threshold) &&
                    rect.left >= (rectContent.left - threshold) &&
                    rect.top <= (rectContent.bottom + threshold) &&
                    rect.left <= (rectContent.right + threshold)
                );
            }

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
