### ISSUE TITLE
when using multi view in same page query wrong

### ISSUE THREAD

**Issue by MahmoudFawzy** [framework7io/framework7#1484]
![image](https://cloud.githubusercontent.com/assets/6429762/24837245/e85f63a6-1d2f-11e7-9685-10f9536f16fe.png)

when using multi view in same page , page query return wrong values

**Comment by nolimits4web** [comment]
What is multi view in same page?

**Comment by MahmoudFawzy** [comment]
I have two view one is *viewMain *, second *viewPop *
when I try refresh *viewMain *from *viewPop *page I get this error

**Comment by nolimits4web** [comment]
Still not clear, would be good to see live example or JSFIddle with the issue

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
