### ISSUE TITLE
DOM checker

### ISSUE THREAD

**Issue by scriptPilot** [framework7io/framework7#1487]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

Even if Framework7 is well-documented, there are several ways to make mistakes in the HTML code (e.g. missing id attributes for tabs). What do you think about a DOM checker, to be enabled in the Framework7 init, which checks all pages according required structure and logs errors to the console.

**Comment by ZanderBrown** [comment]
It could be good to throw warnings in the console for these things

**Comment by J05HI** [comment]
A html code checker would be very much work

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
