### ISSUE TITLE
Status bar disappeared when keyboard appeared

### ISSUE THREAD

**Issue by 0xecute** [framework7io/framework7#1488]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.5.4.
* Platform and Target: IOS

### What you did
Create a **message** page with a status bar and the keyboard.

### Expected Behavior
When the keyboard appeared, the status bar is still visible.

### Actual Behavior
When the keyboard appeared, the status bar disappeared as everything is pushed up.

Actually, I got exactly the same problem as this link of ionic:
https://github.com/driftyco/ionic/issues/932

Can anyone help me about this one? I hang on this problem for 2 days now :(

Thanks in advance

**Comment by mubeenwd** [comment]
I have same problem while using cordova staus bar plugin, but mine was with android not ios but still you can refer to this may be it can help you somewhere.

[https://github.com/framework7io/Framework7/issues/1826](url)

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
