### ISSUE TITLE
Проблема с генерацией параметров в $$.post когда значение пустое

### ISSUE THREAD

**Issue by shastox** [framework7io/framework7#1494]
Если параметры для пост-запроса:
`{k1 :  'v1', k2 : 'v2'}`

В этом случае на сервер придет RAW-запрос: 
`k1=v1&k2=v2`

А если параметры пустые, например: 
`{k1 :  '', k2 : ''}`

На сервер приходит RAW-запрос в виде:
`k1&k2 `

что не правильно, правильно (со знаками "равно"): 
`k1=&k2=`

Важно: почему-то разные веб-серверы по-разному обрабатывают RAW-запрос `k1&k2` : некоторые формируют POST-массив, т.е. 
```
POST= [
'k1' => '',
'k2' => '',
]
```
а некоторые вообще при таких данных не создают POST-массив.

**Comment by PunkSage** [comment]
Could you please translate this to English?

**Comment by shastox** [comment]
Problem with params in $$.post.

This example
`$$.post('http://...', {k1 :  'v1', k2 : 'v2'},...`
will send to server:
`k1=v1&k2=v2`

But this example (empty values)
`$$.post('http://...', {k1 :  '', k2 : ''},...
`
will send to server:
`k1&k2`
It's wrong. Correct data (with **=**):
`k1=&k2=`

Sorry for my English.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
