### ISSUE TITLE
the page  with virtualList,only first load list

### ISSUE THREAD

**Issue by huangyuanyazi** [framework7io/framework7#1500]
my code like this
```js
 myApp.onPageInit('page_record_sales', function () {
    console.debug('page_record_sales初始化')
    ran_data_sales(10, function (result) {
        // alert(result.data)
        myApp.virtualList('#sales_content', {
            // Array with items data
            items: result.data,
            cache:true,
            // Template 7 template to render each item
            template: Template7.templates.page_record_sales_listCard_content
        });
    });
})
```
Only when I first entered the page,the virtual is loaded,And then out into it ,the virtual is not loaded.

**Comment by nolimits4web** [comment]
If your page is not reloaded then this page:init callback won't work again. So would be good to see more code and what do you mean by "then out into it ,the virtual is not loaded"?

**Comment by huangyuanyazi** [comment]
the page:init callback always works.'out into it' means  I click the back button does not contain the back class, contains only back links,then i enter the page again,virtual list does not display.That is to say the code like  <a class='back' href='last.html'>,all going well,but the code like <a class ='' href='last.html'> ,that is not normal

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
