### ISSUE TITLE
Searchbar event trigger after IME input finished

### ISSUE THREAD

**Issue by robinyip** [framework7io/framework7#1508]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.5.4
* Platform and Target: All

### What you did
Use IME input (e.g. Chinese input method) in the searchbar and it doesn't fire the change event after input done.

### Expected Behavior
It should trigger the change event after IME input done.

### Actual Behavior
The searchbar event doesnt attached the "compositionend" and cause nothing happened after IME input is finished.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
