### ISSUE TITLE
IOS problem: SecurityError (DOM Exception 18): The operation is insecure.

### ISSUE THREAD

**Issue by davutkara** [framework7io/framework7#1518]
the error:

![image](https://cloud.githubusercontent.com/assets/10008440/25315673/bab616b0-2861-11e7-9400-43fd9a79dcdd.png)

myapp.js :
![image](https://cloud.githubusercontent.com/assets/10008440/25315679/d2881090-2861-11e7-8497-0a2555089d91.png)

I used this:
`	<meta http-equiv="Content-Security-Policy" content="default-src *; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval'">
	`

I added cordova crosswalk plugin. On ios10 app works well. But On ios9, framework7 does not works.

please help, thank you.

**Comment by ZanderBrown** [comment]
Slightly concerning that you have an error about being unable to load a resource.
Could you share more code? HTML + JS in text form

**Off-topic**:
`var isAndroid = Framework7.prototype.device.android === true` would set `isAndroid` to true if `Framework7.prototype.device.android` has the value of true. So why do the extra logic? `var isAndroid = Framework7.prototype.device.android;` is suffecient

Equally `isAndroid ? true : false`will evaluate to `true` if `isAndroid` is true and to `false` if it's false. That's excess logic.

**Comment by dawiinci** [comment]
Could you please check if the demo files of 2.0.7 work for you? I get this error without doing anything on the code.

macOS 10.13.3 (17D47)

**Comment by DAnn2012** [comment]
On Safari for Mac, as a temporary solution, you can select  "**Disable Cross-Origin restrictions**" from the "**Develop**" menu

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
