### ISSUE TITLE
about refresh page and the query data is losed

### ISSUE THREAD

**Issue by xianghu1314** [framework7io/framework7#1520]
web app framework7 refresh the page but query is invalid,
i refresh  the page  but the query now is invalid?
![image](https://cloud.githubusercontent.com/assets/27937545/25320369/0d07fe02-28d9-11e7-9808-8ec4e411516d.png)

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
