### ISSUE TITLE
page render bugs with vuejs 2.0

### ISSUE THREAD

**Issue by puny-d** [framework7io/framework7#1521]
Here is my code:
 
    myApp.onPageInit('shop', function (page) {
         var demo = new Vue({
               el: page.container
         })
    })

than, In vue2.0,  the 'page-on-center' would be replace with 'page-on-right' on data-page:shop, which would cause opacity to 0;

but it works well with vuejs1.0.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
