### ISSUE TITLE
Picker control issue

### ISSUE THREAD

**Issue by SiddiquiImran** [framework7io/framework7#1524]
This is a (multiple allowed):
* [x] bug

* Framework7 Version: 1.5.4
* Platform and Target: Phonegap Android
* Live Link or JSFiddle/Codepen: PFA APK for the same(plz delete .zip extension from the last to check apk)

### What you did
Have used picker control for picking up option from provided options 

### Expected Behavior
If user clicks on one of the option which is above or below the selected option it should get selected.

### Actual Behavior
It scroll down/up to some random options

[Kitchen sink.apk.zip](https://github.com/nolimits4web/Framework7/files/955099/Kitchen.sink.apk.zip)

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
