### ISSUE TITLE
Another two Smart Select + Popup issues

### ISSUE THREAD

**Issue by tinyCoder32** [framework7io/framework7#1530]
### What you did
I put a smart select inside an initialized popup.

### Expected Behavior
The pop up opens normally, and when user clicks the back button from navbar i was expecting the smart select to get closed.

### Actual Behavior
1- The smart select AND the popup together get closed.
2- If you try again and open the popup, then the smart select don't work anymore (not clickable).

JsFiddle Example here: https://jsfiddle.net/tinyCoder32/L7cpjuvq/

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
