### ISSUE TITLE
iOS notification style error

### ISSUE THREAD

**Issue by scriptPilot** [framework7io/framework7#1532]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

### What you did
Opened notification with the following code:

```
window.f7.addNotification({
  message: 'Some words ...'
})
```

### Expected Behavior
Close button well positioned.

### Actual Behavior
Close button not well positioned.

![bildschirmfoto 2017-04-27 um 19 59 45](https://cloud.githubusercontent.com/assets/19615586/25497271/514c0c7c-2b84-11e7-92d1-8174fddc17e5.png)

![bildschirmfoto 2017-04-27 um 20 06 37](https://cloud.githubusercontent.com/assets/19615586/25497504/108796f6-2b85-11e7-9109-798b0c76d15d.png)

Tested with Chrome web browser and iOS simulator.

**Comment by scriptPilot** [comment]
In addition, this is only to see if there is no title defined.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
