### ISSUE TITLE
how to destory the infinite scroll event

### ISSUE THREAD

**Issue by huangyuanyazi** [framework7io/framework7#1534]
the code like this
```js
var count=0;
$$('.infinit-scroll').on('infinite',function(){
count++
console.log(count)
})
app.detachInfiniteScroll($$('.infinite-scroll'))
app.attachInfiniteScroll($$('.infinite-scroll'))
```
when i use  method up,the method of console.log resumes. that means
how can i bind a new scroll event for $$('.infinit-scroll')

**Comment by tazzkiller** [comment]
i think you need to reset your count variable to 0 after app.detachInfiniteScroll($$('.infinite-scroll'))

**Comment by valnub** [comment]
Did this solve your issue, huangyuanyazi ?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
