### ISSUE TITLE
myApp.device.os not present

### ISSUE THREAD

**Issue by vousys** [framework7io/framework7#1545]
Framework7 Version: 1.0.6
* Platform and Target: WEB

In chrome web browser, before that version, in 1.0.4 I received in
 console.log(myApp.device);
the "os" var as you explain here https://framework7.io/docs/device-api.html
but in 1.0.6 I get this:

android : false 
androidChrome:false
ios : false 
ipad : false 
iphone : false 
ipod : false 
needsStatusBar : function () 
pixelRatio: 1
statusBar : false 
webView : null 
windows : false

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
