### ISSUE TITLE
calendar / datepicker: firstDay:6 causes first week of calendar to be omitted

### ISSUE THREAD

**Issue by tylerbrazier** [framework7io/framework7#1546]
This is a (multiple allowed):
* [x] bug

* Framework7 Version: 1.6.0, 725f50e1784d436f248dd7ff5857d81866c9abc3
* Platform and Target: cordova, ios, android. reproduces on everything
* [JSFiddle](https://jsfiddle.net/s2n1p730/12/)

### What you did
Set `firstDay: 6`. See the jsfiddle

### Expected Behavior
Calendar should start with Saturday (6) as the start of the week (which is it) but the first week of May should be included, along with the last two days of April.

### Actual Behavior
Calendar appears to be using the 6th day of the month as the first displayed in the calendar and the first week of May is missing.

![screen shot 2017-05-05 at 1 55 37 pm](https://cloud.githubusercontent.com/assets/4481528/25760066/abbdc076-319a-11e7-8e4c-451d9d6185d4.png)

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
