### ISSUE TITLE
Date range picker does not work in kitchen sink

### ISSUE THREAD

**Issue by scriptPilot** [framework7io/framework7#1549]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

### What you did
Selected two dates in kitchen sink / date range picker.

### Expected Behavior
Selected range shown in blue.

### Actual Behavior
Selected range not shown.

Google Chrome / macOS

![bildschirmfoto 2017-05-07 um 22 16 50](https://cloud.githubusercontent.com/assets/19615586/25784770/2a90f0ba-3373-11e7-9bca-c5e12f98dc17.png)

**Comment by valnub** [comment]
@ZanderBrown Didn't we have this problem before and wasn't it kinda related to summer/winter time in Russia vs. other countries or so? 😕

**Comment by ZanderBrown** [comment]
Yes in the UK selecting a range that included the GMT/BST switch resulted in a selection off the wrong length.

@scriptPilot what is your timezone?

**Comment by scriptPilot** [comment]
Should be Europe/Berlin.

Dennis

**Comment by valnub** [comment]
Does anyone know where the ticket with the discussion about that problem is? Was it solved/closed back then?

**Comment by ZanderBrown** [comment]
#1385 closed after a PR, think PR may have been reverted @nolimits4web ?

**Comment by scriptPilot** [comment]
@valnub @ZanderBrown @nolimits4web - Instead it works fine in IE11!

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
