### ISSUE TITLE
Select smart multiple select value from Javascript?

### ISSUE THREAD

**Issue by Santoshah** [framework7io/framework7#1555]
How do I select the value of Smart Multiple Select from Javascript everytime when I click on close button ?

**Comment by harrus** [comment]
Good question, I don't know either. There doesn't seem to be anything on the documentation page about this.

**Comment by ZanderBrown** [comment]
Programmatically set the current item or retrieve it?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
