### ISSUE TITLE
Tab Bar Application - Pull To Refresh

### ISSUE THREAD

**Issue by Extracreative** [framework7io/framework7#1563]
Using Tab Bar Application Template 

I'm using `$$('#view-1').on('show',` function(){` as a way of init the pages.

When I pull to refresh it works as expected however after that I can not pull to refresh again. Because the refreshing class is not being removed from from page-content div.

I'm using `$$('.pull-to-refresh-content').removeClass('refreshing transitioning');` as a work around

* [x] bug
* Framework7 Version: 1.60
* Platform and Target: CORDOVA, Android

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
