### ISSUE TITLE
Android INPUT not visible.

### ISSUE THREAD

**Issue by ghost** [framework7io/framework7#1572]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

I have problem to fill input, when keyboard appear the input stay above.

![screen shot 2017-05-25 at 9 41 02 pm](https://cloud.githubusercontent.com/assets/1964848/26476168/3ffd091a-4193-11e7-93f7-9a788e41a10a.png)

![screen shot 2017-05-25 at 9 41 31 pm](https://cloud.githubusercontent.com/assets/1964848/26476169/3fffda64-4193-11e7-8931-d4adda809680.png)

How can I fix it?

I have tested this code:
```javascript
$$("input").on("focus", function(){
    setTimeout(function(){
       $$('.page-content').scrollTo(0, $$("input").offset().top, 500, function(){});
    }, 500);
 });
```

**Comment by valnub** [comment]
You have several mistakes in your code. Try something like this (untested):

```javascript
$$("input[type=text]").on("focus", function(){
  var $this = $(this);
  window.requestAnimationFrame(function(){
    var offset = $this.offset().top;
    $$('.page-content').scrollTop(offset);
  });
});
```

Also, add some `console.log(offset)` statements so you can see what the value of offset is.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
