### ISSUE TITLE
Ajax Form Submit Content type is multipart/form-data always

### ISSUE THREAD

**Issue by kkordinia** [framework7io/framework7#1578]
Ajax Form Submit Content type is multipart/form-data always Even when form element enctype set to application/x-www-form-urlencoded or text/plain. #1556

**Comment by kkordinia** [comment]
i found the soulation. just replace this code in [forms-ajax.js](https://github.com/nolimits4web/Framework7/blob/master/src/js/framework7/forms-ajax.js) file:
```js
 if (method === 'POST') data = new FormData(form[0]);
else data = $.serializeObject(app.formToJSON(form[0]));
```
with this code:
```js
var data = app.formToJSON(form[0]);
```
this soulation work for me.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
