### ISSUE TITLE
Inserting popup with .page class inside stop back link from working

### ISSUE THREAD

**Issue by Schnatteraffe** [framework7io/framework7#1622]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.5.4
* Platform and Target: IOS and Android

### What you did
I need a popup with a navbar on one of my pages. So I used your example from here https://github.com/nolimits4web/Framework7/issues/462 to include the navbar. 

### Expected Behavior
Popup shows up -> Close Link -> Popup closes -> Use any other Link to go to the next page -> Go back from the page to the page with the popup -> Use back again to go further back

### Actual Behavior
Popup shows up -> Close Link -> Popup closes -> Use any other Link to go to the next page -> Go back from the page to the page with the popup -> Using back again does not work anymore

I noticed that as soon as i insert a class .page in any div of the popup, the back link will not work anymore. But only when i go to any next page.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
