### ISSUE TITLE
updateInputValueOnSelect using id not name

### ISSUE THREAD

**Issue by Extracreative** [framework7io/framework7#1625]
in the latest version the input field is being updated with the id not the name. doesn't happen on 1.6.0

* [x] bug

* Framework7 Version: 1.6.4
* Platform and Target:  CORDOVA, IOS, ANDROID.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
