### ISSUE TITLE
SplitView with Material Theme Not Working

### ISSUE THREAD

**Issue by justadaniel** [framework7io/framework7#1627]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.6.2
* Platform and Target: Chrome, Windows, iOS, Android, etc.
* Live Link or JSFiddle/Codepen: Not needed.

### What you did
Pretty much the same basic concept as the example splitview with the exception of it being translated to the material theme.

### Expected Behavior
Have one set of menus on the left, and a detailview on the right.

### Actual Behavior
Page won't load.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
