### ISSUE TITLE
onSlideChangeEnd does not run after prependSlide

### ISSUE THREAD

**Issue by cronoklee** [framework7io/framework7#1628]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: Framework7 1.6.4
* Platform and Target: PhoneGap Android

### What you did
I'm making an infinate swiper. I load a swiper with a single slide the following settings:

```
addSlide( myApp.swiper('#myswiper', {
	onSlideChangeStart: addSlide,
	onSlideChangeEnd: animateActiveSlide,
	onInit: animateActiveSlide
}) )
function addSlide(swiper){
	console.log('onSlideChangeStart')
	ajax('day-'+day(attr('.swiper-slide-active','date'),-1), function(res){
		swiper.prependSlide( res.content );
	})
}
function animateActiveSlide(swiper){
        console.log('animateActiveSlide')
}
```
The idea here is that the swiper.prependSlide() will load a new previous slide with ajax on each iteration so that the user can swipe right through days forever. 

The issue is that after swiper.prependSlide(), onSlideChangeEnd does not run on the new slide. 

**Interestingly:** I can make it run by swiping right so that the new slide is in view, then swiping left back to my previous slide. In this case, onSlideChangeEnd runs twice in a row. Then swiping right again to the new slide, onSlideChangeEnd runs normally on the new slide.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
