### ISSUE TITLE
jdate.js and framework7 calendar component

### ISSUE THREAD

**Issue by kkordinia** [framework7io/framework7#1631]
i use [jdate.js](https://github.com/tahajahangir/jdate) for convert Gregorian dates to jalali in javascript. when[ i set window.date to window.jdate ](http://tahajahangir.github.io/jdate/jalali-highcharts-demo.html) and open calendar in framework7 it work correct for year and month but for showing days of a month not work correctly. and when i click to a day for select a date, calendar go to next or previous month.

![screen shot 2017-06-07 at 19 46 34](https://user-images.githubusercontent.com/22311970/26886169-fa0aac42-4bb9-11e7-9ab3-43ea254c50a3.png)

how to fix this problem for days of month?

**Comment by mer30hamid** [comment]
I fixed some bugs with  jdate.js, I made a pull request and I hope it will be updated soon, you can try my fork of  jdate.js here: https://github.com/mer30hamid/jdate/
also you should consider this bug: #1546 
and you can try it here: https://jsfiddle.net/mer30hamid/xfkx2nz0/7/

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
