### ISSUE TITLE
Material icons allignment issues with Android Kitkat

### ISSUE THREAD

**Issue by sarans73** [framework7io/framework7#1635]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.6.4
* Platform and Target: Android Kitkat 4.2.2

### What you did
Using Material Icons in Cordova Android App

### Expected Behavior
Icons should look normal and work same as Android higher versions.

### Actual Behavior
Icons changing entire alignment of app and difficult to use the app, because of this user not able to install 
the app Androd kitkat version

Before you open an issue, please check if a similar issue already exists or has been closed before.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
