### ISSUE TITLE
About Swipeable Tabs Height Issue

### ISSUE THREAD

**Issue by Key7i** [framework7io/framework7#1637]
This is related to this issue. https://github.com/nolimits4web/Framework7/issues/1189

And i have same problem as well.

If there is a lot of of text in Tab1 and some text in Tab2. Then it will create a scroll and huge blank area on Tab2.. Also if you're at the bottom of Tab1 and swipe to Tab2. It will display bottom of Tab2 with blank area. Have to scroll up to see the actual content in Tab2.

There is about same amount of text in all tabs in this example: http://framework7.io/docs-demos/tabs-swipeable.html That's why there is no difference.

Any solution for this?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
