### ISSUE TITLE
Мisprint

### ISSUE THREAD

**Issue by akoboy** [framework7io/framework7#1644]
https://framework7.io/vue/smart-select.html
misprint at `smart-select-search**N**ar-placeholde`
instead `smart-select-search**B**ar-placeholder`

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
