### ISSUE TITLE
actions-cell not aligned properly in collapsible data table

### ISSUE THREAD

**Issue by surendiranganesan** [framework7io/framework7#1650]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.6.4

### What you did
I am using collapsible data tables to show tables as list view.
If i add any actions-cell like

```
<td class="actions-cell">
            <a class="link icon-only"><i class="icon f7-icons">compose</i></a>
            <a class="link icon-only"><i class="icon f7-icons">trash</i></a>
          </td>
```
In collapsible format its aligned as new rows with collapsible label attribute as null.

I tried the same using 

```
<td class="checkbox-cell">
			<label class="form-checkbox">
			<input type="checkbox" checked><i></i>
			</label>
```

its aligned to the top left as expected

### Expected Behavior
td>actions-cell  in collapsible format should be aligned to the top of the record.

### Actual Behavior
td>actions-cell are displayed as new row with label as null

kindly help me how to fix this out.

regards,
suren

**Comment by nolimits4web** [comment]
Can you show screenshot of what you have?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
