### ISSUE TITLE
framework7 advanced compilation fails with google-closure-compiler

### ISSUE THREAD

**Issue by 20sandeepsingh** [framework7io/framework7#1652]
When trying to compile using webpack google-closure-compiler plugin it generates the bundle but that bundle doesn't work. I chose advance compilation option and it says framework7 is not defined. It works perfectly if I use uglify.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
