### ISSUE TITLE
Swipe and sortable items in list 

### ISSUE THREAD

**Issue by peterel** [framework7io/framework7#1654]
This is a (multiple allowed):
* [x] bug

* Framework7 Version: Framework7 1.5.0, Released on: November 8, 2016
* Platform and Target: Testing on web now, intended for Cordova later on
### What you did
I cant seem to get the Swipe and Sortable functionality to work at the same time for a list. Either one works fine on their own but as soon as I enable sortable `myApp.sortableOpen('.sortable');`, swipe stops working (note that sortable not toggled manually but automatically via javascript, I very much prefer it that way). 

<img width="360" alt="screen shot 2017-06-20 at 17 22 26" src="https://user-images.githubusercontent.com/24371993/27356562-38b9c1b2-560f-11e7-82aa-8f8125c5a53d.png">

### Expected Behavior
I expected that an item becomes both swipeable and sortable.

### Actual Behavior
It only becomes sortable OR swipeable.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
