### ISSUE TITLE
Framework7-react How to pass arguments？

### ISSUE THREAD

**Issue by tanqiyuan** [framework7io/framework7#1658]
excuse me！
Framework7-react How to pass arguments?   I jump to the next page, how to take parameters in the past
Or return the pass parameter?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
