### ISSUE TITLE
Can't change the "Select date" text on date picker

### ISSUE THREAD

**Issue by gianlucag** [framework7io/framework7#1659]
An option to change the "Done" text exists (i.e. toolbarCloseText). No option is available to change the "Select date" text on top of the default date picker panel

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
