### ISSUE TITLE
Stacked modals not working correctly

### ISSUE THREAD

**Issue by adrian-e** [framework7io/framework7#1662]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.6.4
* Platform and Target: All platforms
* Live Link or JSFiddle/Codepen: https://codepen.io/anon/pen/bRoZyo

### What you did
Created a modal and then trigger an alert from inside said modal (it's a validation prompt in the real app).

### Expected Behavior
I would expect the alert to dim the modal content and when it is closed to still have the overlay of the modal to prevent the user from interacting with the rest of the app

### Actual Behavior
The alert does not dim the modal that prompted it, and when the alert is closed the modal's overlay is also closed.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
