### ISSUE TITLE
myApp.formFromData(...) does not re-populate the form upon submit of form.

### ISSUE THREAD

**Issue by peterel** [framework7io/framework7#1664]
This is a (multiple allowed):
* [x] bug

* Framework7 Version: Framework7 1.5.0, Released on: November 8, 2016
* Platform and Target: Web now, Cordova hopefully later

### What you did
Im using formFromData to populate my form. I trigger this in the end of a function with JS like so:
`var formData = {
'bla': bla,
'more': more,
'...': ...
}
myApp.formFromData('#my-form', formData);`

All is well and form is populated. If user submits form, I collect data, store in DB, like so:
`$$('.form-to-data').on('click', function() {
var formData = myApp.formToData('#my-form');
function-to(SubmittDataTo);
}`

### Expected Behavior
Whan a user again opens the form it should be re-populated (as per users last submission). I see that the call is working correctly and via console.log() can see that data is retrieved from BE to FE, but the form is just empty when opened again after submission. 

NOTE: If one does not submit form and just close it, it gets re-populated just fine. NOTE2: If one opens the form a second time after submission, it gets re-populated just fine.

### Actual Behavior
Form is not re-populated after submit.

**Comment by peterel** [comment]
Anyone got any ideas about this or can reproduce? I.e. formdata does not populate form after a submit but does so if form is not submitted.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
