### ISSUE TITLE
[v2] The command $ gulp dist doesn't work!

### ISSUE THREAD

**Issue by BaileyJM02** [framework7io/framework7#1672]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.0
* Platform and Target: $ gulp dist

### What you did
The command $ gulp dist doesn't work due to "Task 'dist' is not in your gulpfile"
### Expected Behavior
I expected it to create a distributable version in the 'dist/'. file

### Actual Behavior
Command Prompt shows:
>[xx:xx:xx] Using gulpfile C:\Fw7\Framework7-v2\gulpfile.js
>[xx:xx:xx] Task 'dist' is not in your gulpfile
>[xx:xx:xx] Please check the documentation for proper gulpfile formatting

*.zip folder includes downloaded repo*
[Framework7-2.zip](https://github.com/nolimits4web/Framework7/files/1117023/Framework7-2.zip)

**Comment by ZanderBrown** [comment]
Probably because it doesn't exist in the V2 gulpfile yet, as thus far it hasn't been needed as V2 is still under development and so there hasn't been a release

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
