### ISSUE TITLE
Alert when clicking the dynamic popover link

### ISSUE THREAD

**Issue by guilhermelirio** [framework7io/framework7#1679]
In this code:

```
$$(document).on('click', '.data-dispensacao', function(){
    var clickedLink = this;

var popoverHTML = '<div class="popover">'+
                      '<div class="popover-inner" align="center">'+
                          '<p><b>Próxima dispensação:</b></p>'+
                          '<p>'+novadata_final+'</p>'+
                            '<div class="list-block">'+
                                '<ul>'+
                                    '<li><a id="atualizar_data" href="#" class="item-link list-button">Atualizar</li>'+
                                '</ul>'+
                            '</div>'+
                        '</div>'+
                    '</div>';
    myApp.popover(popoverHTML, clickedLink);

    $$(document).on('click', '#atualizar_data', function(){        
        myApp.alert("Data atualizada com sucesso!", "Aviso");
    })
})

```

Working, but Popover is on the screen, it looks like it "glues" in the body:

When clicked on the link, inside popover:
http://i.imgur.com/34IPC9Q.jpg

When clicked OK:
http://i.imgur.com/6u9iSms.jpg

How to resolve?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
