### ISSUE TITLE
View history is wrong when a view is initialized with a empty pages element

### ISSUE THREAD

**Issue by blikblum** [framework7io/framework7#1687]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.6.4
* Platform and Target:  web

### What you did
Initialized a view with an empty pages element

### Expected Behavior
No page should be cached or added to view history

### Actual Behavior
A page with name #undefined is added to view history

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
