### ISSUE TITLE
Split view for v2

### ISSUE THREAD

**Issue by krosoftware** [framework7io/framework7#1692]
Hello
does [v2] work with this code: https://framework7.io/examples/split-view-panel/
if not, any chance to create that example for [v2], please?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
