### ISSUE TITLE
Issue with scrollable content in framework7 tab bar

### ISSUE THREAD

**Issue by Rinkuk1993** [framework7io/framework7#1693]
This is a (multiple allowed):
* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

Issue can be seen in demo page of framework 7
   - https://framework7.io/docs/tabbar.html
Platform and Target: CORDOVA, IOS, ANDROID

WHATS THE ISSUE?
If you see, there are 4 tabs in demo for "Tab bar with labels". If content is scrollable and content in tab1 is scrolled to end and user switch to tab 2, content at the end will be shown. This confuses user a lot as they never opened the tab and they don't know where they are in tab2.

Please suggest if there is any way to solve this issue in existing version.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
