### ISSUE TITLE
Modal only showing on index.html

### ISSUE THREAD

**Issue by johndavemanuel** [framework7io/framework7#1695]
Hello! I am using a modal in other pages but it wont show, I follow the code in the documentation, but if I put the "class="alert-text" in any element it show, but in other page it wont?
How to fix that?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
