### ISSUE TITLE
Preprocess won't fire again if it's callback isn't triggered

### ISSUE THREAD

**Issue by WeaponX86** [framework7io/framework7#1696]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.6.3
* Platform and Target: Google Chrome
* Live Link or JSFiddle/Codepen: https://jsfiddle.net/weaponx86/3qLvmfag/6/

### What you did
Created a preprocess function that cancels if the user doesn't have permission to a page. In my jsFiddle demo the "People" link is allowed, the "Other" link is not.

### Expected Behavior
User clicks a link, preprocess is called ASYNCHRONOUSLY. If they have permission, fire next(content), otherwise do nothing. 

### Actual Behavior
User clicks "Other" which cancels preprocess. User then clicks any other link, preprocess is never called again.

**Comment by D-Marc1** [comment]
You have to do `mainView.router.load({url: url, ignoreCache: true})` to refresh the content.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
