### ISSUE TITLE
App initialization -> push state settings -> add a PushStatePageUrlRoot parameter

### ISSUE THREAD

**Issue by ErroneousFatality** [framework7io/framework7#1697]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.6.4
* Platform and Target: CORDOVA, IOS, ANDROID, ETC

My current issue is that my push state links aren't user friendly because they display the full route to the html page, and our team's folder management makes it so that those links are quite long.
Example:
#!//App/mobile/prematch/sportMatches.html

All my mobile application html pages are located inside the "/App/mobile/" folder route, so it would benefit me if there was something like a PushStatePageUrlRoot parameter. 
The string given to that parameter should be prepended (added as a prefix) to every pushstate page route found in the URL, and that would make the full page route from which the Framewok7 could GET the HTML page.

So if my PushStatePageUrlRoot was "App/mobile"

Then my link could look like: #!//prematch/sportMatches.html  (which is much more concise and meaningful to the user)

and the F7 router would still know that that URL leads to the /App/mobile/prematch/sportMatches.html server resource which should be AJAX fetched.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
