### ISSUE TITLE
Documentation Error - "main: true" Initialisation Parameter on addView

### ISSUE THREAD

**Issue by nigelbpeck** [framework7io/framework7#1700]
On the documentation for addView, no [initialisation parameter](https://framework7.io/docs/views.html#view-initialization-parameters) is listed called "main". However, [further down the page](https://framework7.io/docs/views.html#access-to-view-s-instance), within the discussion of accessing a view's instance, it shows an example where "main" is set to "true".

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
