### ISSUE TITLE
switching from rtl to ltr and i18n 

### ISSUE THREAD

**Issue by seme1** [framework7io/framework7#1710]
This is a (multiple allowed):
* [] bug
* [X] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: v1.6.3

It would be nice if there is an easy way pre-built within the framework to allow switching languages (or language direction) from rtl to ltr and vice versa. 
Also, it would be even better if Tempalte7 has rules/guidelines for implementing i18n and the localization of apps with the aid of Framework7.

**Comment by ZanderBrown** [comment]
Currently has no support at all, something worth exploring in V2 @nolimits4web

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
