### ISSUE TITLE
Image Lazy Loading not working correctly

### ISSUE THREAD

**Issue by jozko-pucik** [framework7io/framework7#1711]
This is a:
* [x] bug

* Framework7 Version: 1.6.4
* Platform and Target: Cordova, iOS, Android

### What you did
Using lazy load on images in vertical scroll.

### Expected Behavior
Images will load after they come into the viewport.

### Actual Behavior
Images won't load until they touch the upper viewport threshold.

I have done a bit of code research on this, and I believe that the condition in 'isElementInViewport' in the lazy-loading functions,  is not correct. Actually it is as follows:
```
return (
   rect.top >= (0 - threshold) &&
   rect.left >= (0 - threshold) &&
   rect.top <= (app.height + threshold) &&
   rect.left <= (app.width + threshold)
);
```
and I think it should be:
```
return (
   rect.bottom` >= (0 - threshold) &&
   rect.left >= (0 - threshold) &&
   rect.top <= (app.height + threshold) &&
   rect.right <= (app.width + threshold)
);
```
I changed in inside F7.js and now is working as expected for me. Can you please confirm this?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
