### ISSUE TITLE
ng-repeat behaviour unexpected with swipeBackPage property in angularjs with framework7.

### ISSUE THREAD

**Issue by shyamkushwah** [framework7io/framework7#1714]
I am use swipeBackPage = true property for swipe than ng-repeat behaviour unexpected (ng-repeat bind multiple time) on screen swipe or back button both operation.

please look at attachment.

![capture1](https://user-images.githubusercontent.com/30834627/29075479-224bd9b0-7c70-11e7-8055-f9072eee0784.PNG)

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
