### ISSUE TITLE
smartSelectAddOption not working in popup

### ISSUE THREAD

**Issue by MarioVanDenEijnde** [framework7io/framework7#1715]
The following script line: "if ($('.popup.smart-select-popup').length > 0) return;" blocks the smartSelectAddOption  to update the snart select.
Is there a reason why the code is stopping there?

If I comment the line all seems to work fine.

Kind regards,
Mario

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
