### ISSUE TITLE
Inline Picker / Date-time break on Android

### ISSUE THREAD

**Issue by peterel** [framework7io/framework7#1716]
This is a (multiple allowed):
* [x] bug

* Framework7 Version: Framework7 1.5.0, Released on: November 8, 2016
* Platform and Target: CORDOVA --> ANDROID

### What you did
Followed instructions for Date-Time picker, https://framework7.io/docs/picker.html.

### Expected Behavior
Expecting it should works as example shows. Which it indeed does in the iOS app.

### Actual Behavior
![img_7441](https://user-images.githubusercontent.com/24371993/29095888-d698ba60-7c92-11e7-9e09-3c1373264169.JPG)

I.e. the "day field", "year field" as well as "hour field" only show the first value, rest is missing. Month and minute seems to be OK though. NOTE: One can "scroll" day and hour "fields", its just that they are not visible in the picker when scrolling. Any ideas on why this is?

**Comment by peterel** [comment]
Has anyone else seen this behavior or is it just my old HTC one that is acting up maybe?

**Comment by peterel** [comment]
Pretty please. Anyone thats seen this before and/or has a possible fix/workaround?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
