### ISSUE TITLE
Define item alignment for grid

### ISSUE THREAD

**Issue by albru123** [framework7io/framework7#1718]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

It would be great if we could use helper classes choose alignment for grid items. With grid being flexbox it should be easily doable and would come handy for stuff like image thumbnail galleries where you would expect items to align to the left instead of the default center alignment.

Exposing other flexbox properties through helper classes may be appreciated by others as well, but as flexbox contains a lot of properties, it might bloat the API.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
