### ISSUE TITLE
Events needed for when pages made active or inactive

### ISSUE THREAD

**Issue by nigelbpeck** [framework7io/framework7#1719]
It seems that the event structure for pages is missing a way to identify when a page is actually made active to the interface, and when it is made inactive. "init" only fires when loaded to the DOM, so doesn't work on going back to a page, "beforeremove" is only when removed from the DOM, and nothing directly to do with leaving the page, "beforeanimation" is only when pages are animated in.

It would be great if there was a reliable event for when a page is made active to the screen, and when it was made inactive and left the screen. I have found [workarounds](https://github.com/nolimits4web/Framework7/issues/698), but they don't work for all cases.

My current use case is that I need to save state for the app, which is using dynamic pages, and none of the workarounds help reliably. There is no way at all to attach to when a page is leaving the screen, and I am currently using a hack in "beforeremove" since one page is removed each time, albeit not the one that is leaving the screen.

We will perhaps look at submitting a PR for this once we get through current deadlines in a month or two, but wanted to submit an issue for it.

**Comment by nolimits4web** [comment]
I can recommend you to use `beforeanimation`. This event only occurs for the page that will be now active (`from` event parameter shows where it comes from (right or left)). So, when such event is happen, you made its page "active" and all other pages as "inactive". Anyway, i know there is an issue with it. This issue is fixed in upcoming v2 release, where page events a bit refactored and more obvious to use

**Comment by nigelbpeck** [comment]
Thanks, I've found `beforeanimation` useful, except I don't always animate and it doesn't cover initial loading, for example. What I'm looking at doing is putting all my routing through a central handler, to create my own place for it that always runs. It will be great to have something native to the framework to handle that once V2 arrives. Looking forward to that. Thanks for the great framework it's been very helpful with our project.

**Comment by vvarda** [comment]
Guys, how can I emulate that "pages made active or inactive"? Any ideas?

I need it for pages without "slide animation" and with bottom toolbar.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
