### ISSUE TITLE
Problems with history by using router.back() / back class

### ISSUE THREAD

**Issue by Garfredo** [framework7io/framework7#1723]
If I use router.back() or a link with back class for navigating to the previous page, I always get the same behaviour:
The page transists to the previous page but the page events deliver the page name (data-page) from the page before the previous page. 
This happens also on smart selects.

**Comment by yankopetrov** [comment]
Yes, same problem here. Because FW7 load previous of previous, all my page properties are override with previous.

**Comment by Garfredo** [comment]
You have to deactivate _**preloadPreviousPage**_

var mainView  = myApp.addView('.view-main', {
    preloadPreviousPage:  false
});

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
