### ISSUE TITLE
how to show streaming details data from external js

### ISSUE THREAD

**Issue by johanan7** [framework7io/framework7#1726]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* Platform and Target: cordova and android

### What you did
I am creating a radio app with centovacast server. on my index.html i am showing NOW PLAYING widget using external js from centovacast. `<script language="javascript" type="text/javascript" src="http://audiocp.globaliway.co.in:2199/system/streaminfo.js"></script>`  and in body tag i am adding a code that shows the details `<p id="pplayer"> Now Playing: <br> <span class="cc_streaminfo" data-type="title" data-username="suvifm"></span> </p>`  now it works fine when i check it in the browser and now playing track is shown.
when i compile it in pgb as apk, the app is not showing any stream details.

### Expected Behavior
the app should show streaming track details in the span class.

### Actual Behavior
nothing shown.

P.S. Remember, an issue is not the place to ask questions. You can use [Stack Overflow](http://stackoverflow.com/questions/tagged/framework7)
for that or join the #framework7 channel on irc.freenode.net, where we will be more
than happy to help answer your questions.

Before you open an issue, please check if a similar issue already exists or has been closed before.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
