### ISSUE TITLE
Having some issues with logo 

### ISSUE THREAD

**Issue by nackerr** [framework7io/framework7#1728]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: EXACT RELEASE VERSION OR COMMIT HASH, HERE.
* Platform and Target: iOS
* Live Link or JSFiddle/Codepen: https://simplr.website/app

### Actual Behavior
So I’ve set up a login script using a tutorial I found. I have a tab bar with 4 tabs and basically on every view it checks if the session/cookie is set. After logging in it correctly works and sets the session, but only the first view removes the login screen. The other three are still acting like there is no session. Is there anyway to do a manual reload of the app? Because if you close the app then reopen it works fine.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
