### ISSUE TITLE
Lost material style on dynamically added components

### ISSUE THREAD

**Issue by matejicekme** [framework7io/framework7#1730]
Hi there,

Got an issue with F7 + vue. When I create item dynamically I lost the material theme (when using material). For example I build a form depending user previous input and when building it, the used theme = IOS theme.
Got “material: true” on my F7 app initialization and commented the IOS css files.Anyone ?

Thank you

**Comment by nolimits4web** [comment]
Well, can't really understand how it is possible. Are you trying to change theme dynamically?

**Comment by eslindsey** [comment]
This seems to work well for me, even for components I add dynamically:

```javascript
var myApp = new Framework7();
if (myApp.device.android) {
    $$("#css_main").attr('href', 'f7/css/framework7.material.min.css');
    $$("#css_colors").attr('href', 'f7/css/framework7.material.colors.min.css');
}
```

In the `<head>` of `index.html` I have the following:

```html
<link id="css_main" rel="stylesheet" href="f7/css/framework7.ios.min.css">
<link id="css_colors" rel="stylesheet" href="f7/css/framework7.ios.colors.min.css">
```

**Comment by chittattoo** [comment]
chit

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
