### ISSUE TITLE
fastClicks:handleTouchEnd function bug on some android device

### ISSUE THREAD

**Issue by nmbean** [framework7io/framework7#1734]
This is a (multiple allowed):
* [x] bug

* Framework7 Version: 1.6.4.
* Platform and Target: Android.

function "handleTouchEnd" in app.initFastClicks,

                if (!trackClick) {
                    if (!activeSelection && needsFastClick) {
                        if (!(app.device.android && !e.cancelable)) {
                            e.preventDefault();
                        }
                    }
                    return true;
                }
when div is scrolling,
program will execute "e.preventDefault();", app.device.android is true and e.cancelable is aslo true.
so the scrolling has been stop immediately, the html page seems like lag......
please fix...

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
