### ISSUE TITLE
issue with a accordion component 

### ISSUE THREAD

**Issue by andrew-basilioos** [framework7io/framework7#1736]
i am using framework7 last version , and my app hierarchy is like that : 
- vue router-view
- vue children are loaded within router-view
- one of those children is the root of framework7 app
when i navigate between "the root of framework7 which is a component" and any other component , the accordion animation start to stuck and act unexpectedly but it work good before navigation done .

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
