### ISSUE TITLE
Bug in Sub Navbar

### ISSUE THREAD

**Issue by ghost** [framework7io/framework7#1740]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.6.0
* Platform and Target: ANDROID AND IOS ( USING IOS THEMES )

### What you did
If you have one Page with sub Navbar and when you go to next page ( in portait mode ) and next you rotate the phone to  landscape mode ) the buttons navbar preview page stay there.

### Expected Behavior
sub navbar be totatly hidded to when I go to next page.

temporary fix I did it:

myApp.onPageBeforeRemove('main-screen', function (page) {
	$$(".subnavbarfix").hide();
});
I send hide to subnavbar, so I can rotate my phone and it works fine.

myApp.onPageBack('timeline-calendar', function (page) {
	$$(".subnavbarfix").show();
});
Turn back visible the subnavbar when turn back to page.

You can see the problem here:

Main Page OK.
![screen shot 2017-08-17 at 12 06 45 am](https://user-images.githubusercontent.com/1964848/29394369-21dba82c-82e0-11e7-88d2-659fe28ff687.png)

Next Page OK.
![screen shot 2017-08-17 at 12 07 01 am](https://user-images.githubusercontent.com/1964848/29394370-21dd023a-82e0-11e7-9a1b-1d2e3ff41abb.png)

Rotate screen to landscape Problem :(
![screen shot 2017-08-17 at 12 07 16 am](https://user-images.githubusercontent.com/1964848/29394371-21e04134-82e0-11e7-98a4-cec0dd36b9f5.png)

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
