### ISSUE TITLE
slider height bug? 

### ISSUE THREAD

**Issue by wggCode** [framework7io/framework7#1745]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.6.4
* Platform and Target: IOS Safair ,  Chrome 

### What you did
html:

`
<div class="page" data-page="pageHome">
    <div class="page-content">
      
        <div class="swiper-container swiper-1">
            <div class="swiper-pagination"></div>
            <div class="swiper-wrapper">
                <div class="swiper-slide">
                    <img src="resource/images/slide1.png" alt="">
                </div>
                <div class="swiper-slide">
                    <img src="resource/images/slide1.png" alt="">
                </div>
                <div class="swiper-slide">
                    <img src="resource/images/slide1.png" alt="">
                </div>
            </div>
        </div>
        
    </div>
</div>
`
css:
`

.swiper-slide {
    background: #fff;
    box-sizing: border-box;
    border: 1px solid #ccc;
}

.swiper-slide img{
    width: 100%;
}

.swiper-pagination-bullet-active{
    opacity: 1;
    background: #ffafbc;
}

`
![12](https://user-images.githubusercontent.com/4902425/29488018-413c9454-8535-11e7-9c95-ae59eed01138.png)

The  "swiper-slide" div is 7 pixels larger than the image , why?

**Comment by wggCode** [comment]
img{
  display:block;
}

The problem is finally solved

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
