### ISSUE TITLE
Scrolling data-table right/left not working with option swipePanel

### ISSUE THREAD

**Issue by cyberbeat** [framework7io/framework7#1746]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

It seems to be the same problem as with the slider in a bug I reported before. When I configure the app with swipePanel: "left", and try scroll a data-table to the left, only the left panel is revealed. There should be added an exception for this case in the swiping-panel-code.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
