### ISSUE TITLE
pages.query does not decode '+' spaces

### ISSUE THREAD

**Issue by eslindsey** [framework7io/framework7#1747]
This is a (multiple allowed):
* [x] bug

* Framework7 Version: 1.6.4
* Platform and Target: IOS, ANDROID

### What you did
```javascript
// /#!/error.html?msg=There+was+a+problem
myApp.onPageInit('error', function (page) {
    $$('#error_msg').text(page.query['msg']);
});
```

See [this Stack Overflow comment](https://stackoverflow.com/questions/1005676/urls-and-plus-signs#comment14903296_1006074) for a discussion about the "standards-ness" of the plus sign in queries.

### Expected Behavior
`page.query['msg']` should contain `"There was a problem"`

### Actual Behavior
`page.query['msg']` contains `"There+was+a+problem"`

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
