### ISSUE TITLE
VirtualScroll disappears after data update, if has been scrolled before

### ISSUE THREAD

**Issue by hellofarhan** [framework7io/framework7#1755]
### Expected Behavior
When the data updates, the list should be updated and not disappear.

### Actual Behavior
In a virtual scroll list, if the data is updated (or the subscription to data removed and re added) and the list has been scrolled down a couple pages, the list becomes blank until the user scrolls down a bit.

Check similar ionic issue:
https://github.com/ionic-team/ionic/issues/9722

**Comment by nolimits4web** [comment]
Will be good to see live example with the issue like jsfiddle. If you update DOM directly you need to call some VL methods to update it

**Comment by hellofarhan** [comment]
Please check this:

https://1drv.ms/v/s!Ag9glYTBCmdPg0zghk-saimZ-JFX

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
