### ISSUE TITLE
Smart Select Layout become mess when inside in a accordion

### ISSUE THREAD

**Issue by johndavemanuel** [framework7io/framework7#1756]
I am using smart select and If I put it in a accordion the tile and selected values become display block

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
