### ISSUE TITLE
Swiping to change calendar month in datepicker opens panel instead

### ISSUE THREAD

**Issue by Hissvard** [framework7io/framework7#1763]
This is a:
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)
___

* Framework7 Version: 1.5.0

### Reproducing
App with swipePanel enabled and a datepicker (I think anywhere, but I personally found the issue with an inline calendar)

### Expected Behavior
When swiping over a datepicker, the month should change without the panel being opened (just like it happens with Swiper)

### Actual Behavior
The datepicker is ignored and the panel is opened instead.

**Comment by SpiderNeo1** [comment]
Up !

I have the same problem.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
