### ISSUE TITLE
Action Sheet Grid Documentation?

### ISSUE THREAD

**Issue by JosephShenton** [framework7io/framework7#1766]
This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* Framework7 Version: 2.0 beta 1
* Platform and Target: ios
Hi there, so I saw your kitchen sink for action sheet grid so i put that into app.js but after that it didn't work neither did if i did it from kitchen sink as well. I was wondering if you could give me the required javascript code to be able to do `onclick="share();"`. If possible?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
