### ISSUE TITLE
Bug in tabs.js showTab function

### ISSUE THREAD

**Issue by guylando** [framework7io/framework7#1767]
If there are multiple tab-links in a page which use data-tab property and tab is changed then only one of the links will be removed the active css class. If they use the href property then they all will be removed the active css class.

Need to change tabs.js showTab function from:
```
if (oldTabId) oldTabLink = $('.tab-link[href="#' + oldTabId + '"]');
                // Search by data-tab
                if (!oldTabLink || oldTabLink && oldTabLink.length === 0) {
                    $('[data-tab]').each(function () {
                        if (oldTab.is($(this).attr('data-tab'))) oldTabLink = $(this);
                    });
                }
```
To something like:
```
if (oldTabId) oldTabLink = $('.tab-link[href="#' + oldTabId + '"]');
                // Search by data-tab
                if (!oldTabLink || oldTabLink && oldTabLink.length === 0) {
                    oldTabLink  = $('[data-tab]').filter(function(index, el) {
    return oldTab.is($(this).attr('data-tab'));
});
                }
```

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
