### ISSUE TITLE
Tabbed layout hide toolbar

### ISSUE THREAD

**Issue by guylando** [framework7io/framework7#1769]
How to hide toolbar automatically in tabbed layout without using javascript? I saw in the following link that this functionality should have been implemented but cant find it in docs: https://muut.com/i/framework7/getting-started:hide-toolbar-on-scroll-when

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
