### ISSUE TITLE
prevent bounce on popup

### ISSUE THREAD

**Issue by rainxie** [framework7io/framework7#1770]
This is a (multiple allowed):
[x] bug

Framework7 Version: v 1.6.3
Platform and Target:  IOS

I add "&lt;preference name="UIWebViewBounce" value="false" /&gt;" to config.xml.
I have prevented bounce on page,
but I don't prevent bounce on popup.

![screenshot001](https://user-images.githubusercontent.com/6250927/29914138-049fc35c-8e6a-11e7-9b0e-a61d33ba3f96.jpg)

**Comment by nolimits4web** [comment]
Issue is closed because of outdated, irrelevant or not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
