### ISSUE TITLE
Virtual-list emptied itself while transitioning through pages

### ISSUE THREAD

**Issue by ytbryan** [framework7io/framework7#1786]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.6.5 (also tested on 1.6.4
* Platform and Target: It was tested on macOS and also observed on iOS

### What you did
Please watch https://youtu.be/TmZ5FIb9KwU

### Expected Behavior
The virtual-list should not be emptied while transitioning between pages. It should retain its items. 

### Actual Behavior
Referring to the video, the virtual-list was emptied upon transition from third-level page to second-level page

**Comment by nolimits4web** [comment]
Issue is closed because of outdated, irrelevant or not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
