### ISSUE TITLE
Calling swiper.appendSlide([]) throws an error

### ISSUE THREAD

**Issue by anrikun** [framework7io/framework7#1789]
Calling `swiper.appendSlide([])` throws an error.

This is a bug.
Framework7 Version: 1.6.5

Line 16946:
`            if (typeof slides === 'object' && slides.length) {`
should be replaced by:
`            if (typeof slides === 'object' && 'length' in slides) {`
because it doesn't catch slides.length === 0

**Comment by anrikun** [comment]
There is the exact same error in both `prependSlide()` and `removeSlide()`

**Comment by nolimits4web** [comment]
Issue is closed because of outdated, irrelevant or not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
