### ISSUE TITLE
Lazyloading images in Swiper

### ISSUE THREAD

**Issue by vafa-k** [framework7io/framework7#1792]
![untitled](https://user-images.githubusercontent.com/31923620/30375945-b20f8880-989f-11e7-8f32-a7baad9a9bb2.png)

As seen in the picture above, I have created a page containing a Swiper element.
i have changed the swiper css attributes a bit so each slide has 85% width of the screen. this way the user is able to see a little preview of the next slide.

.swiper-slide{
	height: 280px;
	overflow: hidden;
	border-radius: 8px;
	width: 85% !important;
}
.swiper-slide .img{
	width: 100%;
       /*100px less height to give some space for headings and text */
	height: 180px;
	background-color: #f2f2f2;
	background-position: center;
	background-size: cover;
	border-radius: 8px;
}

myApp.swiper('.myswiper', {
                        slidesPerView: "auto",
                        spaceBetween: 16,
                        freeMode: false,
                        lazyLoading: true,
                    }); 

myApp.initImagesLazyLoad('div.swiper-lazy');

now the problem is that only the image inside the active swiper-slide loads but I neet the image in the next slide to lazy-load too.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated, irrelevant or not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
