### ISSUE TITLE
messages always scroll

### ISSUE THREAD

**Issue by appedemic** [framework7io/framework7#1798]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.6.5
* Platform and Target: Browser, Android, iOS

### What you did
I have a `<f7-messages :scrollMessages="false">` sitting somewhere at at the bottom of the page (on load outside of visible area).

### Expected Behavior
I expect the `<f7-page>` not to scroll to the bottom but stay on top.

### Actual Behavior
The `<f7-page>` scrolls to the bottom where the `<f7-messages>` is sitting, despite scrollMessages being fase.

This is due to a line in messages.js

https://github.com/framework7io/Framework7/blob/master/src/js/framework7/messages.js#L199

The  `m.scrollMessages(0);` will always scroll the page to the messages part.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated, irrelevant or not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
