### ISSUE TITLE
[v2] prevent context menu on android

### ISSUE THREAD

**Issue by pi0** [framework7io/framework7#1817]
This is a (multiple allowed):
* [x] enhancement
* [x] feature-discussion (RFC)

Currently, touch call-out is disabled for IOS using `-webkit-touch-callout` which is awesome, also same seems is added into [material css](https://github.com/framework7io/Framework7/blob/807a25b302c859067e59f97da7c3fa956ec12358/src/less/material/intro.less#L25) but it is not working as stated in [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-touch-callout) it is only implemented as an experimental thing into safari. 

<img src="https://user-images.githubusercontent.com/5158436/30731780-424753fa-9f7c-11e7-81a1-3279d9ad8460.png" width="300px">

Long tap context menu on native-like F7 apps in android chrome is little annoying. From [this](https://stackoverflow.com/questions/3413683) question seems the only available method would 
 be preventing `window.oncontextmenu`event like this:

```js
window.oncontextmenu = function(event) {
     event.preventDefault();
     event.stopPropagation();
     return false;
};
```

I've opened this issue instead of a PR to ask first is there any reason not using this approach?

Another thing about browser-specific touch events. Is selectable text something expected?

<img src="https://user-images.githubusercontent.com/5158436/30731656-8ca2a0ae-9f7b-11e7-9cef-e2b60dba27ec.png" width="300px" align="center">

/ping @nolimits4web

**Comment by pi0** [comment]
Update: I've added some experimental changes into nuxt7 demo for this (https://nuxt7.surge.sh) for a quick review :)

**Comment by J05HI** [comment]
@nolimits4web
Looks fine and easy :)

**Comment by danish1023** [comment]
+1

**Comment by nolimits4web** [comment]
Ok, i agree with disabling context menu. But let's do it for mobiles only (when we assume it is used in apps). Not sure about disabling it totally because F7 also can be used in desktop web sites and web apps. For same reason let's keep user-select as it is. It is not hard to add one custom line of code if it is required.

**Comment by nolimits4web** [comment]
We can add context menu disabling at https://github.com/framework7io/Framework7/blob/v2/src/modules/touch/touch.js#L580

**Comment by nolimits4web** [comment]
Issue is closed because of outdated, irrelevant or not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
