### ISSUE TITLE
Calling smartSelectOpen() causes error

### ISSUE THREAD

**Issue by theryan722** [framework7io/framework7#1835]
This is a (multiple allowed):
* [x] bug

* Framework7 Version: 1.6.4.
* Platform and Target: Web.
### What you did
I called myApp.smartSelectOpen('#mysmartselecthere');

### Expected Behavior
The smart select would open.

### Actual Behavior
I get an error and nothing happens:

```
framework7.min.js:19 Uncaught TypeError: Cannot read property 'disabled' of undefined
    at window.Framework7.r.smartSelectOpen
```

**Comment by nolimits4web** [comment]
You should pass there element with "smart-select" class rather than `<select>`

**Comment by nolimits4web** [comment]
Issue is closed because of outdated, irrelevant or not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
