### ISSUE TITLE
DevExpress ChartJS not working 

### ISSUE THREAD

**Issue by Dhanasekaranjones** [framework7io/framework7#1836]
I have used the latest framework 7 plugin (1.6.4)

And also i have use the **DevExpress ChartJS Version: 13.2.9**.

I have use the swipe event in latest framework 7 plugin in my application.

And i have swipe the page to hide the charts and values & sometime show the graph correct.

I have attach the screenshots:

![localhost-808-xccsvn-platforms-android-assets-www-phone-index-iphone html iphone 6 plus 1](https://user-images.githubusercontent.com/31949378/30898244-fb52c02e-a377-11e7-9433-38b007ec9fb0.png)
![localhost-808-xccsvn-platforms-android-assets-www-phone-index-iphone html iphone 6 plus](https://user-images.githubusercontent.com/31949378/30898250-048833d6-a378-11e7-913b-43927ce46c0c.png)

**Note: This issue occurred in swipeout the page**

**Comment by nolimits4web** [comment]
Issue is closed because of outdated, irrelevant or not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
