### ISSUE TITLE
swipe list and checkbox together

### ISSUE THREAD

**Issue by rkl1994** [framework7io/framework7#1837]
This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* Framework7 Version: 1.5.0

## What you did
I use swipe list now and make a list like ios mail app, it can swipe to left and do actions. 

![123](https://user-images.githubusercontent.com/5527455/30946031-3614d1a4-a434-11e7-9e32-b2515ff38071.PNG)

![456](https://user-images.githubusercontent.com/5527455/30946083-77af216e-a434-11e7-9fd7-460bd48e75ee.PNG)

## Expected Behavior
However, I want to add checkbox to the list together with swipe feature.
What I want to do is I can both swipe to left and checkbox can be called after click 'Edit' button or triggered by other actions(Just like the native ios mail app).

## Actual Behavior
What I do now is to write two 'ul' tag. one is for swipe class, another is for checkbox. After click 'Edit' button, swipe class will be set to display:none and checkbox class will be displayed. Click 'Cancel' button, swipe class will be displayed and checkbox class will be hidden.

Is this the best practise to bind checkbox and swipe list together? Or is there any solution I can use only one ul tag to have the same feature(checkbox list with swipe)? 

Thank you

**Comment by nolimits4web** [comment]
Issue is closed because of outdated, irrelevant or not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
