### ISSUE TITLE
the "loop" Parameter with photobrowser will cause the media that jump to the next one

### ISSUE THREAD

**Issue by bau720123** [framework7io/framework7#1839]
This is a Bug

* Framework7 Version: 1.6.5
* Platform and Target: Windows 7 Google Chrome 61.0.3163.91 64 bits
* Live Link or JSFiddle/Codepen: https://www.littlebau.com/photobrowser.html

### What you did
Test the "loop" Parameter with photobrowser

### Expected Behavior
step1︰when I click the "With Video" button，it will appear the photobrowser and show **1 of 3**
step2︰click the "Close" button in the left up corner and click the "With Video" button again，it will appear the photobrowser and show **1 of 3**

### Actual Behavior
step1︰when I click the "With Video" button，it will appear the photobrowser and show **1 of 3**
step2︰click the "Close" button in the left up corner and click the "With Video" button again，it will appear the photobrowser and show **2 of 3**
step3︰click the "Close" button in the left up corner and click the "With Video" button again，it will appear the photobrowser and show **3 of 3**
step4︰click the "Close" button in the left up corner and click the "With Video" button again，it will appear the photobrowser and show **1 of 3**
step5 and after that︰always show **1 of 3**

### Conclusion
after some survey，I finally know where the problem is
if I dismiss the "loop" Parameter，it will show just like the Expected Behavior
but if I set the "loop" Parameter，it will show just like the Actual Behavior

**Comment by bau720123** [comment]
no any reply ?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated, irrelevant or not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
