### ISSUE TITLE
[v2] Timeline problems

### ISSUE THREAD

**Issue by l41lt0n** [framework7io/framework7#1851]
I have a strange problem with timeline version2 using md thmes.
The year and month text stay appear / disappear.

I have tested in emulator and my iphone / ipad the same problem.

https://imgur.com/a/60lP0

**Comment by lailton** [comment]
Only to complement, It happens in the iOS themes too.

**Comment by nolimits4web** [comment]
See this issue too, looks like some iOS-specific rendering issue

**Comment by lailton** [comment]
Yes, I think so.

**Comment by lailton** [comment]
@nolimits4web,

I have tested and the [v1] don't have this issue.

**Comment by webeditors** [comment]
I get this is 1.6.5

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
