### ISSUE TITLE
[v2] On browser back button click 

### ISSUE THREAD

**Issue by J05HI** [framework7io/Framework7#1859]
@nolimits4web
Could you please add an event to prevent the router back on browser back button click to do something else?

**Comment by nolimits4web** [comment]
No, because if you use browser back button then, i believe, you use push state, and in this case it is not possible as there is no way to prevent native browser's history event so it will change URL to the previous one anyway. And even if we prevent router loading (it is possible) then we will have a mess with URLs. So no go for this

**Comment by J05HI** [comment]
@nolimits4web
Oh okay
