### ISSUE TITLE
iOS invisible text on textarea in accordion

### ISSUE THREAD

**Issue by somuelle-tmt** [framework7io/framework7#1866]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: v1.6.5
* Platform and Target: Cordova, iOS 11
* Live Link or JSFiddle/Codepen: https://jsfiddle.net/ttc9trw1/

### What you did
Created a textarea in an accordion element. Opened Accordion, wrote text.
See Link above for a live demo.

### Expected Behavior
Text visible

### Actual Behavior
Text invisble

This only happens in Mobile Safari, tested on iOS 10 and iOS 11.
If you close and open the accordion, the text is visible, but this is very confusing for users!

**Comment by nolimits4web** [comment]
Issue is closed because of outdated, irrelevant or not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
