### ISSUE TITLE
material-inputs.js and  forms-textarea.js are not included in custom core build

### ISSUE THREAD

**Issue by blikblum** [framework7io/framework7#1882]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: master - v1
* Platform and Target: web

material-inputs.js (handles floating-label) and forms-textarea.js (handles  resizable text area) are not included in core custom build. Is only included with forms module

But in [documentation](http://framework7.io/docs/custom-build.html) forms module accounts only for  Form Storage, Form Data and Ajax Form Submit not accounting for floating label or resizable textarea

IMO the docs should be updated or material-inputs.js and forms-textarea.js should be included in core build

**Comment by nolimits4web** [comment]
Issue is closed because of outdated, irrelevant or not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
