### ISSUE TITLE
The month is wrong in calendar / datepicker!

### ISSUE THREAD

**Issue by cronoklee** [framework7io/framework7#1889]
This is a (multiple allowed):
* [x] bug
* Framework7 Version: 1.6.5 Released on: September 7, 2017

Open the material view calendar on the framework7 homepage and inspect a day. Today is 16th **OCTOBER** 2017, or in standard ISO format: **2017-10-16**

This is the element F7 has generated for today. 
Not only is it missing leading zeros, it's showing **SEPTEMBER**  16th 2017

`<div data-year="2017" data-month="9" data-day="16" class="picker-calendar-day picker-calendar-day-today" data-date="2017-9-16"><span>16</span></div>`

This is an issue with JS getMonth() function starting at zero for January. However I think a fix should be added to F7 to make the datepicker practical for real world uses. The dates provided by the picker really need to be compatible with server-side languages to be useful.

**Comment by cronoklee** [comment]
Suggested fix: **src/js/framework7/calendar.js :541**

```
//date with leading zeros:
var datestring = ('0' + dayDate.getDate()).slice(-2) + '-'
	+ ('0' + (dayDate.getMonth()+1)).slice(-2) + '-'
	+ dayDate.getFullYear();
rowHTML += '<div data-year="' + dayYear + '" data-month="' + dayMonth + '" data-day="' + dayNumber + '" class="picker-calendar-day' + (addClass) + '" data-date="' + dateString + '"><span>'+dayNumber+'</span></div>';
```

**Comment by nolimits4web** [comment]
Issue is closed because of outdated, irrelevant or not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
