### ISSUE TITLE
[v2] SplitView

### ISSUE THREAD

**Issue by l41lt0n** [framework7io/framework7#1952]
@nolimits4web,

Congratulations again for all your time dedicated for this excellent project!!!

Can you make a post in your blog about (create) Views [v2] look like you did for routers ?

Thanks

**Comment by nolimits4web** [comment]
Issue is closed because of outdated, irrelevant or not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
