### ISSUE TITLE
can you update daily for vue version? as f7 is too big for mobile web to load.this year, vue is most popular as will as my web choise for develop.

### ISSUE THREAD

**Issue by owey0312** [framework7io/Framework7#1960]
can you update daily for vue version? as f7 is too big for mobile web to load.this year, vue is most popular as will as my web choise for develop.

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. 

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
