### ISSUE TITLE
f7.mainView.router.back({url: 'main', force: true})  working without animation

### ISSUE THREAD

**Issue by adsprosto** [framework7io/framework7#1961]
f7.mainView.router.back(); - working with animation
f7.mainView.router.back({url: 'main', force: true}); - working without animation

**Comment by nolimits4web** [comment]
Issue is closed because of outdated, irrelevant or not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
