### ISSUE TITLE
[v2] Using scrollable tab bar with swipeable tabs as part of section in a page creates lot of nested scrollbars to appear

### ISSUE THREAD

**Issue by rapgithub** [framework7io/framework7#1965]
Using  scrollable tab bar with swipeable tabs as part of section in a page creates lot of nested scrollbars to appear, i was using the scrollbar tab bar as part of a page in a section and above the scrollbar I have a swiper gallery and the scrollbar tab bar generate a lot of scrolling bars for the content and scrolling the page up and down creates also a lot nested scrolling bars to appear... 
 
I found that height:100% at some point affects this but i do not find a solution for the page to be scrolling smooth and without nested scrollbars appearing all the time.. 

the code it is like below inside the page: swiper first and below the toolbar tabbar tabbar-scrollable
with swipeable tabs

< div class="swiper-container demo-swiper-gallery-top">
....

< / div >

and below:

< div class="toolbar tabbar tabbar-scrollable">

      < div class="tabs-swipeable-wrap">

....

**Comment by nolimits4web** [comment]
Issue is closed because of outdated, irrelevant or not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
