### ISSUE TITLE
Back button and smart select

### ISSUE THREAD

**Issue by djvonavi** [framework7io/framework7#1967]
Hi, my Cart component has two smart selects, when I select something in it, I click back button and get this error:
<img width="700" alt="2017-11-21 15 21 15" src="https://user-images.githubusercontent.com/11898500/33072220-a5f4a614-cecf-11e7-9ed3-9d570114bcc8.png">

who has same problem?
-------------------
Привет, есть компонент на vue Cart, в нем есть смарт селект, после того как выбрать что то в нем, при нажании кнопки назад вот эта ошибка стреляет, кто нибудь сталкивался?

**Comment by nolimits4web** [comment]
Any chance to check the live example or something more informative?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated, irrelevant or not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
