### ISSUE TITLE
Link Image in routes

### ISSUE THREAD

**Issue by M4ttscx** [framework7io/framework7#1983]
This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

Hi Vladimir,

I would like to know how to put a link in the path of the routes:

Example:

{
   path: '/ test /: name /: tel /: img /',
   componentUrl: './pages/test.html',
},

Link to access:

/test/Matheus/344565633/https://img.com/43454.png/

Is it possible to do that?

**Comment by J05HI** [comment]
@M4ttscx
You could create a page with <img src="yourImage">

**Comment by nolimits4web** [comment]
Issue is closed because of outdated, irrelevant or not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
