### ISSUE TITLE
Autocomplete dropdown error

### ISSUE THREAD

**Issue by owen-mills** [framework7io/framework7#1990]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 1.6.5.
* Platform and Target: Phonegap, emulated using Ripple

### What you did
I created an app with a searchbar that I added a dropdown `autocomplete` to. When I added the autocomplete, I get an error.
### Expected Behavior
I expected the autocomplete with dropdown to work
### Actual Behavior
I get the error `Uncaught TypeError: Cannot read property 'top' of null`

I am using material theme btw

**Comment by nolimits4web** [comment]
Issue is closed because of outdated, irrelevant or not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
