### ISSUE TITLE
[v2] combine routable tabs with swipeable & pushState

### ISSUE THREAD

**Issue by kinimodmeyer** [framework7io/framework7#1999]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: v2

```
<div class="tabs-swipeable-wrap">
        <div class="tabs tabs-routable">
            <div class="page-content tab" id="tab1">
                   xyz
            </div>
            <div class="page-content tab" id="tab2">
                   xyz
            </div>
            <div class="page-content tab" id="tab3">
                   xyz
            </div>
        </div>
    </div>
```

if you use pushState and params then in the adress the correct params will be replaced with e.g. "/:id/:name/:federation/"

```
<div class="tabs-swipeable-wrap tabs-routable">
        <div class="tabs">
            <div class="page-content tab" id="tab1">
                   xyz
            </div>
            <div class="page-content tab" id="tab2">
                   xyz
            </div>
            <div class="page-content tab" id="tab3">
                   xyz
            </div>
        </div>
    </div>
```

will change tab but will not update pushState or the active flag

**Comment by nolimits4web** [comment]
Issue is closed because of outdated, irrelevant or not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
