### ISSUE TITLE
Uncaught TypeError: myApp.addView is not a function

### ISSUE THREAD

**Issue by rajaramtt** [framework7io/framework7#2009]
Getting Started With Framework7 get error "myApp.addView is not a function" and framework7.ios.colors.min.css not found in dist css folder .

Currently i am using framework7-2.0.2

**Comment by mitchellfranklin** [comment]
Hi @rajaramtt , from V1 to V2 this has changed so you will need to adjust your code to match

I will assume your trying to load the mainview of the application in this instance.

In your app definition it now needs to look like this

```
// Set your theme
var theme = 'ios';  //md = Material - ios = iOS


// Init App
var yourapp= new Framework7({
  root: '#app',
  theme: theme,
  routes: routes, /*if your not going to use routes comment this line out*/
});
```

Now with the CSS this has changed, you only need to define `<link rel="stylesheet" href="css/framework7.min.css"> ` as this is now handled by the theme declaration.

to add the root of the app which is the main view in the first div of the body as the id of app or which ever valur you added as the root.

```
<body> 
        <div id="app"> 

```

**Comment by rajaramtt** [comment]
@mitchellfranklin thanks for your quick response... But document still showing old version code.

https://framework7.io/docs/get-started.html

@nolimits4web @bencompton Please update the document and quick start

**Comment by azanatta** [comment]
The documentation is not up to date.
I'm getting "myApp.addView is not a function" error using the code in the "get started" docs page.

I've also tried with the fix proposed by @mitchellfranklin, but I'm still getting the error. I can't find documentation for version 2.0.2 (downloaded using bower).

Thanks

**Comment by mitchellfranklin** [comment]
Hi @azanatta V2 is a complete re-write, you will need to give @nolimits4web sometime to be able to set this up as you can imagine its not that simple. If you can provide a source sample of your code I can have a look, if your upgrading from V1 to V2 then a full review is required as to allow for the new enhancements a lot of the code appears to be renewed so is not a simple copy paste.

If you look at the Kitchen Sink @nolimits4web has done a fantastic job of writing the required code in each page i.e. modals, alerts, search etc. so you can also look at this as well - to be honest this is what I have used to rebuilt three apps and build 1 new one because it really does help to view the kitchen sink.

**Comment by azanatta** [comment]
@mitchellfranklin thank you for the answer, sure I know about the great job he's made and I appreciate it really a lot, I was just pointing out that the online docs are not for the v2 (or almost this is what it seems to be), so people could get confused when trying to use framework7 for the first time :)

**Comment by onewoorks** [comment]
try change this -> _addView_ to _view.create_

`var mainView = myApp.addView('.view-main', {`
to 
`var mainView = myApp.view.create('.view-main', {`

**Comment by pravin021989** [comment]
I am also facing this problem.I have tried 
var mainView = app.view.create('.view-main', {

but not work

Please guide me.
