### ISSUE TITLE
[v3] Router navigate issue

### ISSUE THREAD

**Issue by danish1023** [framework7io/framework7#2010]
@nolimits4web 
app.router.navigate('/');
it redirect us to http://example.com/#!/

Expected: http://example.com/

**Comment by J05HI** [comment]
Same here

**Comment by ZanderBrown** [comment]
Well as F7 is using shebang it would be the expected although a bit silly for /

**Comment by J05HI** [comment]
@ZanderBrown
Then I should use ~/ or what 😅

**Comment by darkdante83** [comment]
Same here, i made a workaround by making the pages stacked and changing the root route to a page instead of a url: 

 {
    path: '/',
    pageName: 'main',
    name: 'home',
  }

Now the 'home' button works and shows the correct html instead of 404 or empty page. However, if i go back to the original page (back button, router back etc), i get a 404  ... dooh
