### ISSUE TITLE
Сжимается StatusBar после разблокировки iPhone

### ISSUE THREAD

**Issue by shastox** [framework7io/framework7#2013]
Когда поле ввода находится внизу, то при нажатии на клавиатуру, весь контент уходит вверх, перекрываясь со StatusBar, а когда клавиатура убирается, то все восстанавливается,  - это нормальное поведение. 

Но если **именно в момент** показа клавиатуры (и наплытия контента на StatusBar) заблокировать Айфон, а потом сразу разблокировать и убрать клавиатуру, то StatusBar не восстановится:

![2017-12-16_19-47-31](https://user-images.githubusercontent.com/1684567/34072524-df9e59ae-e299-11e7-8fdf-28e0ca770867.png)

Правда, если опять заблокировать и разблокировать Айфон - высота StatusBar'a восстановится и все будет ок.

Не знаю, чей это баг, но в v1 его не было.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant or not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
