### ISSUE TITLE
Popover Positioned incorrectly after switching page

### ISSUE THREAD

**Issue by sorryjack** [framework7io/framework7#2014]
Specs:
I am using template: framework7 + vue.js + Webpack + Cordova

I use popover component, its positioned correctly when first click, then I switch to another page, back again to the page that has popover, click it, and the popover displayed incorrectly (not on the clicked text). Click again, and its positioned correctly. I think it reads the duplicated component at the hidden/cached page. IDK. Please help.

Pic: 1st clicked
![screenshot_6](https://user-images.githubusercontent.com/6811578/34088042-8398856c-e3d9-11e7-902e-c19d9c515f8a.png)

pic: after switching page
![screenshot_7](https://user-images.githubusercontent.com/6811578/34088064-9fea4e08-e3d9-11e7-8f15-d23f1195b123.png)

**Comment by kevinqqnj** [comment]
to solve, simply give your popovers different id, and open them with id.
e.g.
```
<f7-link popover-open="#pop-id1" @click="">Open pop1</f7-link>
<f7-popover class="popover-menu" id="pop-id1">
...
```

another popover:
`<f7-popover class="popover-menu" id="pop-id2">`

**Comment by sorryjack** [comment]
I will try.. thanks. will inform if this work or not..

**Comment by nolimits4web** [comment]
Issue is closed because of outdated, irrelevant or not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
