### ISSUE TITLE
allowTouchMove property of Swiper.js is not working in framework7

### ISSUE THREAD

**Issue by Intraview-in** [framework7io/framework7#2015]
For More Details
[click here](https://stackoverflow.com/questions/47807969/allowtouchmove-property-of-swiper-js-is-not-working-in-framework7)

**Comment by nolimits4web** [comment]
Framework7 v2?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated, irrelevant or not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
