### ISSUE TITLE
[list-view] .item-row with item-after renders content not in row

### ISSUE THREAD

**Issue by nimo23** [framework7io/framework7#2126]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2

Using such a layout:

![acc](https://user-images.githubusercontent.com/3045549/35176083-584343b8-fd77-11e7-83ca-95adc364f726.png)

renders the two buttons within the `.item-after` not in one line (second buttons is not visible)
. Using this:

![acc2](https://user-images.githubusercontent.com/3045549/35176121-884bf424-fd77-11e7-886e-f34fc902ae0b.png)

the buttons within `.item-after` renders right.

The doc says, ".item-after" can be used for buttons and the like, so it should also work when using item-row.

**Comment by nolimits4web** [comment]
`item-cell` sets `display: block` on element, so it is expected behavior. Also you uses item-row on item inner which is already row-like (flex-element).

Anyway, there are typography classes to tweak flex box behavior, F7 can't cover all possible cases for all kind of layouts, don't hesitate to use custom styles to tweak it as you need:

http://framework7.io/docs/typography.html#element-display
```
<div class="item-cell item-after display-flex">...
