### ISSUE TITLE
Offline route

### ISSUE THREAD

**Issue by patsadow2** [framework7io/framework7#2143]
Hello,

Is there anyone who changed routing to working offline without ajax ??

Br :)

**Comment by nolimits4web** [comment]
> READ THIS BEFORE POSTING ISSUE:

Please, don't ask questions on GitHub! Do you want to ask a question? Are you looking for support? The Framework7 forum (http://forum.framework7.io) and Stack Overflow (http://stackoverflow.com/questions/tagged/framework7) are the best places for getting support

- If the issue is about Framework7 v1 then it is more likely it will be closed because v1 is not maintained anymore
- If the issue is related to Swiper, then please open it in Swiper repository at https://github.com/nolimits4web/Swiper
- If the issue is related to Dom7, then please open it in Dom7 repository at https://github.com/nolimits4web/Dom7
- If the issue is related to Template7, then please open it in Dom7 repository at https://github.com/nolimits4web/Template7
- If the issue is related to Framework7-Vue, then please open it in Framework7-Vue repository at https://github.com/framework7io/framework7-vue
