### ISSUE TITLE
google maps plugin

### ISSUE THREAD

**Issue by alextapia007** [framework7io/framework7#2154]
Hi.
Im using https://github.com/mapsplugin/cordova-plugin-googlemaps, in framework 7 v1.6.5 works well, but in v2 i cant use the map, its showing but cant touch, move, zoom, etc.
i remove the framework7.css and work... but without style, please help

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/framework7io/framework7/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
