### ISSUE TITLE
[Range slider]'s change event not trigger once after dragging but triggering many times during dragging.

### ISSUE THREAD

**Issue by qudou** [framework7io/framework7#2162]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: EXACT RELEASE VERSION OR COMMIT HASH, HERE.
* Platform and Target: PLATFORM CLIENT YOU ARE TARGETING SUCH AS CORDOVA, IOS, ANDROID, ETC.
* Live Link or JSFiddle: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_. You can start from forking the following JSFiddle template: [JSFiddle](https://jsfiddle.net/nolimits4web/o2ejupu1/)

### What you did
EXPLAIN WHAT YOU DID, PREFERABLY WITH CODE EXAMPLES, HERE.

### Expected Behavior
EXPLAIN WHAT IS TO BE EXPECTED, HERE.

### Actual Behavior
EXPLAIN WHAT IS ACTUALLY HAPPENING, HERE.

P.S. Remember, an issue is not the place to ask questions. You can use [Stack Overflow](http://stackoverflow.com/questions/tagged/framework7)
for that or join the #framework7 channel on irc.freenode.net, where we will be more
than happy to help answer your questions.

Before you open an issue, please check if a similar issue already exists or has been closed before.

**Comment by nolimits4web** [comment]
This is how `input` event behaves natively

Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/framework7io/framework7/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.

**Comment by qudou** [comment]
Sorry sir, I was talking about the change event, but I described it as a input event.
