### ISSUE TITLE
[v2] Router go back problem when define 404 route

### ISSUE THREAD

**Issue by weijian1** [framework7io/framework7#2266]
This is a (multiple allowed):
* [x] bug

* Framework7 Version: 2.0.10
* Platform and Target: iOS
* Live Link or JSFiddle: 
http://php-developer.herokuapp.com/frontend/

![framework7](https://user-images.githubusercontent.com/9735144/37216431-b3d84364-23f5-11e8-9afd-f4205e45f397.gif)

### What you did
When i open view pushState and define the 404 page in routes array, go to page 2 and go to page3, then back page 2 and back to home page. When page 2 back to home page, the page show 404 page, not go to home page.
```js
var app = new Framework7({
  root: '#app',
  name: 'My App',
  id: 'com.myapp.test',
  theme: 'ios',
  routes: [
    {
      path: '/',
      url: 'page1.html',
    },
    {
      path: '/page2/',
      url: 'page2.html',
    },
    {
      path: '/page3/',
      url: 'page3.html',
    },
    {
      path: '(.*)',
      url: '404.html',
    }
  ],
  view: {
    pushState: true
  }
});
```

### Expected Behavior
Go to the home page.

### Actual Behavior
Go to the 404 page.

**Comment by nolimits4web** [comment]
Push state configured not correctly. According to your example, `pushStateRoot` parameter must be set to `/frontend/`

**Comment by cyberbeat** [comment]
This bug should not have been closed. I copied the example, and modified it to
- pushState = false (so that the pushStateRoot parameter should not be relevant anymore)
- make the 404-path async for debugging purpose (always calling reject())

Please have a look:
https://www.wordwar.org/f7bugs/index.html

Multiple strange things happen (when clicking: page2->page3->back->back):
a) on each back-click the 404-route is called
b) the last back-click does not work, and the routeTo-Path is set to the url, but it should be '/'

(see also console.log output)

**Comment by lvdiep** [comment]
I have the same issue. Any new update?

**Comment by yin-zhi-jun** [comment]
I found a solution

`    view:{
        stackPages:true
    }`

![image](https://user-images.githubusercontent.com/25472301/51734786-7d545800-20c0-11e9-80ad-cb7db332d1ee.png)

**Comment by lscorrea** [comment]
show funcionou para mim! parabéns, mesmo com o push ligado.
