### ISSUE TITLE
BUG: cordova ios app animatePages not smooth

### ISSUE THREAD

**Issue by guylando** [framework7io/framework7#2274]
I have a bug which appears specifically on iphones cordova app. When clicking on a normal link which should transition to another dom cached page then the animation is not smooth.
While debugging the issue I see that the animatePages function is executing two lines:
leftPage.removeClass(removeClasses).addClass('page-from-center-to-left');
rightPage.removeClass(removeClasses).addClass('page-from-right-to-center');
where the first line is executed with animation and moves current page a little to the left and then the second line is executed without any animation. 
I am using framework7 version 1.6.4.
This is a critical bug for us, do you have any idea please on what could cause this?

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/framework7io/framework7/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.

**Comment by nolimits4web** [comment]
And 1.x version is not maintained anymore
