### ISSUE TITLE
nice to have Utils.promise.all

### ISSUE THREAD

**Issue by jonybuzz** [framework7io/framework7#2312]
This is a:
* [ ] bug
* [X] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.x.

It is really helpful the utils.promise feature. I deleted bluebird (Promise polyfill) from my project thanks to F7 browser support but I had to bring it back because I needed the **Promise.map()** and **Promise.all()** functions

**Comment by nolimits4web** [comment]
Worth checking I think

**Comment by J05HI** [comment]
Yeah would be very nice!

**Comment by blikblum** [comment]
I go in the opposite route: the custom Promise implementation should be removed.

Recently there's a trend to ship less JS code as possible, being a cornerstone for Progressive Web App (PWA).

Since one of the goals of F7 v4 is to target PWA, i would remove the more code possible including the custom Promise implementation. Also it should be modular so features not required could be dropped. In my case for example i dont use Template7

This will allow devs that do not target old browsers provides a better experience. In the same time is pretty easy to support old browsers with polyfills or services like polyfill.io.

References:
https://medium.com/dev-channel/the-cost-of-javascript-84009f51e99e
https://github.com/ionic-team/stencil#polyfills (example of framework that targets small code size / PWA - from ionic team)

**Comment by J05HI** [comment]
@blikblum
If you use tree shaking the size is irrelevant.
You'll only pack functions which are being used.

**Comment by blikblum** [comment]
> You'll only pack functions which are being used.

In this case no, because Utils will be used elsewhere and holds a reference even if not used by me.

Anyway this issue is irrevevant now since the custom promise was ripped from v4
