### ISSUE TITLE
iosSwipeBack && mdSwipeBack 2.2.0

### ISSUE THREAD

**Issue by sanbenedetto** [framework7io/framework7#2318]
iosSwipeBack && mdSwipeBack 
has a bug

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/framework7io/framework7/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.

**Comment by sanbenedetto** [comment]
ok now

each view in views ('.views .tabs') must have 'view-main' class
didn't know that
sorry
