### ISSUE TITLE
Framework 7/Phonegap App not working in Android 5.0 and below 

### ISSUE THREAD

**Issue by Donald3d** [framework7io/framework7#2342]
I don't know whats wrong , I have tried everything possible.And my clients are already getting pissed at me 
For some reasons clicking buttons onclick,ontouchstart,ontouchend (I have tried them all), don't respond in android 5.0 and below, it works fine in 6.0
I don't know what to do again , I have been on this for about a week
Has anybody experienced this , do you know how to resolve this ?
Please help, my client is pissed at me and I don't know what to do again 
Thanks for such a wonderful framework.I really appreciate the work you put into it

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/framework7io/framework7/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
