### ISSUE TITLE
两个Tab，各有两个两个搜索框，这两个搜索框搜索的内容冲突

### ISSUE THREAD

**Issue by FatSper** [framework7io/framework7#2388]
有时候，我用第一个tab中的搜索框搜索搜索出来后，我用第二个在搜索，返回第一个刚刚搜索的数据和列表的数据就全为空了。试问？可不可以为单机tab增加单机事件。
求问。

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/framework7io/framework7/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
