### ISSUE TITLE
A tag with attributes' target="_blank" and download not working

### ISSUE THREAD

**Issue by pluckannfeel** [framework7io/framework7#2400]
i dont know but in normal, this seems to work fine. but with framework 7, its not working. Or is there something im missing? 
im aware of 'external' class but it only allows to go to page not open in a different tab

```
<a href="/uploads/somefile.txt" download="somefile.txt">download file</a>

<a href="gotosite.com" target="_blank">go to page</a>
```

**Comment by nolimits4web** [comment]
You need to use Cordova InApp Browser plugin
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/framework7io/framework7/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
