### ISSUE TITLE
[V3] Choppy left/right panel animation on android

### ISSUE THREAD

**Issue by burtontanner** [framework7io/framework7#2463]
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 3.0.0-beta.15
* Framework7 React Version: 3.0.0-beta.15
* Platform and Target:  CORDOVA, ANDROID.

### What you did
cloned react template repo
```
git clone https://github.com/bencompton/framework7-react-static-template my-app            
```
then installed on android phone via cordova. 

### Expected Behavior
Left and right panel to animate smoothly like the popup.

### Actual Behavior
Animation is a pretty choppy on android phones.

I know you can only expect so much out of an android phone but the popup still has a clean animation.

Thanks!

**Comment by bencompton** [comment]
To clarify, that template is actually still on Framework7 V1--or did you happen to upgrade it to V3?

**Comment by burtontanner** [comment]
@bencompton Sorry I didnt clarify, I did checkout the v3 branch.

**Comment by nolimits4web** [comment]
Android webview is (usually) a way slower than iOS one or Android Chrome. It highly depends on Android version and device manufacturers because some of them don’t use Chrome webview and use own implementations/forks. I can recommend you try crosswalk-webview, or try to simplify panel appearance, for example by removing box-shadow on it
