### ISSUE TITLE
How to center Navbar Page Title?

### ISSUE THREAD

**Issue by guyuewuren** [framework7io/framework7#2478]
The app's page title is usually centered.For example, login registration page, etc. How to center Navbar Page Title？Navbar layout is now：

```
<div class="navbar">
    <div class="navbar-inner">
        <div class="left">Left</div>
        <div class="title">Page Title</div>
        <div class="right">Right</div>
    </div>
</div>
```

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/framework7io/framework7/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
