### ISSUE TITLE
文档有错误

### ISSUE THREAD

**Issue by qiaoqiao10001** [framework7io/framework7#2483]
template7===>自动编译
id="myTemplate" 是模板的id，后面可以通过这个id来方法这个模板

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/framework7io/framework7/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
