### ISSUE TITLE
Git/NPM v3.0 dist folder

### ISSUE THREAD

**Issue by sashberd** [framework7io/framework7#2494]
Hi guys

We have [open issue](https://github.com/cdnjs/cdnjs/issues/12877)that your lib is out of version on cdnjs.
We found that for version 3.0.0 there is no dist folder, nor on git, as on npm, which was exists in previous 2.x.x versions
Can you add the dist folder or from v3.0.0 you folder stuct will different from previous verions
Thanks

**Comment by nolimits4web** [comment]
Hey @sashberd 

Yes, since v3 this repo is a multi repo (one repo for multiple NPM packages) now and there is no `dist` folder anymore. What was in `dist` before now moved to `packages/core`, and this folder is also the root for `framework7` NPM package, and 
* `packages/vue` - is root/dist for `framework7-vue` NPM package
* `packages/react` - is root/dist for `framework7-react` NPM package
