### ISSUE TITLE
default routes not work

### ISSUE THREAD

**Issue by Tracis** [framework7io/framework7#2550]
![image](https://user-images.githubusercontent.com/7136882/43630453-f1c15c28-9732-11e8-8533-b91901d71b6f.png)

I used a default route in routes. But when no routes  match the path, the page will show the home page but not the 404 page. Default routes not work.

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/framework7io/framework7/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
