### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by vascubrian** [framework7io/framework7#2563]
Hello, any one can help
my app.js

app.onPageInit('index', function (page) {
// Do something here for "about" page
var template = $$('#index').html();
var compiledTemplate = Template7.compile(template);
app.request.get('localhost/*****/home/TestAjax', function (data) {
var context = data;
var html = compiledTemplate(context);
});
}).trigger();

my view
<script id="index" type="text/template7">

Hello, my name is {{firstName}} {{lastName}}
</script>

its not working

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/framework7io/framework7/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
