### ISSUE TITLE
Popup Component can't use

### ISSUE THREAD

**Issue by tetor** [framework7io/framework7#2571]
* Framework7 version: 3.1.1
* React.js version: 16.4.1
* Platform and Target:  iOS 11 Cordova app and Android 8 Chrome browser

### Describe the bug
When I use Popup Component, error occur. Because `self.$f7` doesn't have the `popup` prop in `componentDidMount`.

### Screenshots
![screen shot 2018-08-10 at 22 04 02](https://user-images.githubusercontent.com/2876841/43959780-eacf4516-9cea-11e8-9e9b-6ce066dadfd0.png)

**Comment by tetor** [comment]
I import `Popup` and use in render() 😓

**Comment by nolimits4web** [comment]
You still doing something wrong, would be good to see more details

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/framework7io/framework7/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
