### ISSUE TITLE
Input Component can't use

### ISSUE THREAD

**Issue by tetor** [framework7io/framework7#2572]
* Framework7 version: 3.1.1
* React.js version: 16.4.1
* Platform and Target: iOS 11 Cordova app and Android 8 Chrome browser

### Describe the bug
I imported Input Component and used in render() but error occurred. Because `f7.input` prop is undefined.

### Screenshots
![screen shot 2018-08-11 at 2 03 19](https://user-images.githubusercontent.com/2876841/43971071-b9ff019a-9d0a-11e8-94b5-816f9264e9bc.png)

**Comment by nolimits4web** [comment]
You still doing something wrong, would be good to see more details

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/framework7io/framework7/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
