### ISSUE TITLE
URL is different from the corresponding page address.

### ISSUE THREAD

**Issue by fxk01** [framework7io/framework7#2599]
When I reopen the third level address, the corresponding address and page when the back returns to the previous level are incorrect, how to solve...

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/framework7io/framework7/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
