### ISSUE TITLE
New Pad

### ISSUE THREAD

**Issue by Tjomaaa96** [framework7io/framework7#2707]
* Framework7 version: [e.g. 3.0.0]
* Platform and Target: [e.g. iOS 11 Cordova app, or Android 8 Chrome browser]
* Live Link or JSFiddle: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_. You can start from forking the following JSFiddle template: [JSFiddle](https://jsfiddle.net/nolimits4web/o2ejupu1/)

### Actual Behavior
Explain what is actually happening

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/framework7io/framework7/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
