### ISSUE TITLE
bundle.js: These dependencies were not found

### ISSUE THREAD

**Issue by nurdus** [framework7io/framework7#2820]
Hi, everyone.
I'm trying import:
import framework7 from 'framework7/framework7.esm.bundle.js'
import framework7-vue from 'framework7/framework7-vue.esm.bundle.js'

BUT get 
These dependencies were not found:
* framework7-vue/framework7-vue.esm.bundle.js in ./src/main.js
* framework7/framework7.esm.bundle.js in ./src/main.js

What's wrong?

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/framework7io/framework7/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
