### ISSUE TITLE
About F7 V4 statusbar on Android

### ISSUE THREAD

**Issue by JazzHunter** [framework7io/framework7#3019]
I am using F7 cli (with latest cli, f7 and f7-vue version) to create a new App project for android, the default statusbar overlay setting created by F7-cli is false. I wannt to set the overlay statusbar style for Android. I have set the following：
1. Cordova config.xml preference StatusBarOverlaysWebView preference value -->>true
2. App.vue f7params.statusbar  overlay-->>true,  androidOverlaysWebView -->>true

The overlay effect is not good as in IOS, there is some issues:
1. The statusbar is not overlayed when App opened, unless focus in an input element
2. Sometimes The statusbar is overplayed but without F7's statusbar

Wondering if there is any other setting I could do...

Thanks for your reply

**Comment by nolimits4web** [comment]
Because it doesn't work correctly on Android by itself. Keep it as it was by default:

* StatusBarOverlaysWebView must be `false` for Android
* `androidOverlaysWebView: false` in app parameters
* `overlay: Framework7.device.cordova && Framework7.device.ios || 'auto',` in app parameters

And set `androidBackgroundColor` paramter to required value
