### ISSUE TITLE
DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by AliMamed** [framework7io/framework7#3135]
* Framework7 version: [4.2.2]
* React.js version: [16.0.0]
* Platform and Target: [any]
* Live Link or JSFiddle: https://jsfiddle.net/alimamed/zjkc8udr/

### Describe the bug
DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### To Reproduce
1. Open Fiddle (you can use this link for full view https://fiddle.jshell.net/alimamed/zjkc8udr/show#)
2. Click on "menu" link
3. Click on "list" link in panel
4. Click each Item on master page
5. Click on "menu" link again
6. Click on "about" link in panel
7. Click on "menu" link again
8. Click on "list" link again - you get the crash

Spent some time on debugging but could not understand the behaviour that leads to the error.

**Comment by nolimits4web** [comment]
Hi, check the "red" note in this section http://framework7.io/docs/view.html#master-detail

When navigating from master page to something else (like in your case to another master page), we need to use `reloadAll` on router link. Because new Master page suppose to have other Detail pages. So it needs to be reloaded. Here is the working example https://jsfiddle.net/kvxpcnu3/

And I can also recommend to use `reloadDetail` on links that load detail pages within master

**Comment by AliMamed** [comment]
Great thanks
