### ISSUE TITLE
Can't reload page

### ISSUE THREAD

**Issue by emmanuel39hanks** [framework7io/framework7#3141]
I am using Framework7-react i use the Framework7-cli but when i pick the Tabs it doesn't show things in Tabbed View just single page view
and when i change code in the files it doesn't update shows the Single page template even if i edit the files and when i use http-server it shows this when i go to the src folder 
"<% if (process.env.TARGET === 'web') { %> <% } %>
<% if (process.env.TARGET === 'cordova') { %> <% } %>
"

**Comment by nolimits4web** [comment]
Please provide more details

**Comment by emmanuel39hanks** [comment]
When i type 'npm start' and start coding it doesnt reload i just get the same starter template

**Comment by nolimits4web** [comment]
Please fill the issue template correctly with all the steps

**Comment by emmanuel39hanks** [comment]
Alright 
and i had sent this to your mail "
Hello How are you?
My name is Emmanuel Haankwenda am a 14 year old from Africa,Zambia
i am a Full Stack JavaScript Developer and i was checking alternatives to React Native that use React since i use React alot then i found Framework7 
about 4 days ago and i really like it.
to make it reach out to more people
i would advice you guys to create a Youtube Channel where you teach Framework7 inside out and beginner to expert tutorials t would be really
easy for beginners to learn Framework7, regular Hackathons to promote it .
cause alot of beginners prefer videos than documentation and videos more people would use it if there is enough learning material like let me say React Native etc.

Many thanks,
"

**Comment by nolimits4web** [comment]
Great. But still :) In order to get your issue resolved please fill the issue form, i can't understand what the issue you have and where:

* Framework7 version: [e.g. 3.0.0]
* React.js version: [e.g. 16.0.0]
* Platform and Target: [e.g. iOS 11 Cordova app, or Android 8 Chrome browser]
* Live Link or JSFiddle: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_. You can start from forking the following JSFiddle template: [JSFiddle](https://jsfiddle.net/nolimits4web/vxb8oyke/)

### Describe the bug
A clear and concise description of what the bug is.

### To Reproduce
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

### Expected behavior
A clear and concise description of what you expected to happen.

### Actual Behavior
Explain what is actually happening

### Screenshots
If applicable, add screenshots to help explain your problem.

### Additional context
Add any other context about the problem here.

**Comment by emmanuel39hanks** [comment]
I found the solution the problem was that i didn't check my package.json file scripts there no start script
