### ISSUE TITLE
F7在IOS WEBVIEW中的问题

### ISSUE THREAD

**Issue by 361877802** [framework7io/framework7#3247]
F7-vue版中在有虚拟列表的页面  用swiperback  滑动返回的时候动画很卡，此问题只出现在IOS下，XCODE10.2.1  F7版本是4.4.6

* Framework7 version: [e.g. 3.0.0]
* Vue.js version: [e.g. 2.0.0]
* Platform and Target: [e.g. iOS 11 Cordova app, or Android 8 Chrome browser]
* Live Link or JSFiddle: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_. You can start from forking the following JSFiddle template: [JSFiddle](https://jsfiddle.net/nolimits4web/jcwzqovz/)

### Actual Behavior
Explain what is actually happening

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/framework7io/framework7/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
