### ISSUE TITLE
Prompt should have immediate focus

### ISSUE THREAD

**Issue by holtwick** [framework7io/framework7#3284]
When opening `prompt` it should be possible to have immediate focus on the text field. (iOS)

See demo on https://framework7.io/docs/dialog.html#prompt 

This video shows first the current behavior and then the one triggered by `window.prompt('Sample')` with a custom implementation in `WKWebView`: https://holtwick.de/download/20190806-215744-prompt.mp4

Indeed, when doing the same in Safari there is no auto-focus as well. But workflow wise I think it makes sense to allow immediate trigger of focus.

**Comment by cepm-nate** [comment]
The issue is iOS does not allow us to open the keyboard via any non-touch initiated event. So while it is possible to focus the input, the keyboard will only open if a parent event was initiated via the user. This is a highly annoying "feature" for iOS webapps, and I hope someday they remove the limitation, or make it into a "this site is trying to open the keyboard without your initiating it. [Always Allow] [Always Deny]" prompt / setting.

**Comment by holtwick** [comment]
I see, this is indeed a show stopper. Just FYI, there is a hack for that on the native side to avoid that limitation if you really have to: https://stackoverflow.com/a/48623286/3297914
