### ISSUE TITLE
datetime-local does not work in v5 (vue)

### ISSUE THREAD

**Issue by BananaAcid** [framework7io/framework7#3416]
It does not show the dialog anymore.

Not in my v4 code, nor in in the v5 demo.

https://framework7.io/vue/inputs.html

```
  <f7-list-input
    label="Date time"
    type="datetime-local"
    placeholder="Please choose..."
  >
    <f7-icon icon="demo-list-icon" slot="media"></f7-icon>
  </f7-list-input>
```

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/framework7io/framework7/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.

**Comment by BananaAcid** [comment]
... your demo is not showing the selection dialog as in v4 anymore. Easy to reproduce: open the mentioned link to the docs.
