### ISSUE TITLE
Why close the issue #3423? The problem is obvious in the image i appended in 3423.

### ISSUE THREAD

**Issue by woodman250** [framework7io/framework7#3430]
Why close the issue #3423? The problem is obvious in the image i appended in 3423.
Could you give some reason for closing #3423?
[https://github.com/framework7io/framework7/issues/3423](https://github.com/framework7io/framework7/issues/3423)

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/framework7io/framework7/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.

**Comment by woodman250** [comment]
I describe the problem clearly (both version and link) in issue #3423 and appended a picture, but you give nothing feedback expect closing.
