### ISSUE TITLE
Uncaught TypeError: Cannot set property 'f7View' of undefined

### ISSUE THREAD

**Issue by yash970** [framework7io/framework7#3458]
### 

> [`**<!--**`](

- 

- [ ] @ #1. url

)

READ THIS BEFORE POSTING ISSUE:

Please, don't ask questions on GitHub! Do you want to ask a question? Are you looking for support? The Framework7 forum (http://forum.framework7.io) and Stack Overflow (http://stackoverflow.com/questions/tagged/framework7) are the best places for getting support

- If the issue is about Framework7 v1/v2 then it is more likely it will be closed because v1/v2 is not maintained anymore
- If the issue is related to Swiper, then please open it in Swiper repository at https://github.com/nolimits4web/Swiper
- If the issue is related to Dom7, then please open it in Dom7 repository at https://github.com/nolimits4web/Dom7
- If the issue is related to Template7, then please open it in Template7 repository at https://github.com/nolimits4web/Template7
-->

* Framework7 version: [e.g. 3.0.0]
* Platform and Target: [e.g. iOS 11 Cordova app, or Android 8 Chrome browser]
* Live Link or JSFiddle: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_. You can start from forking the following JSFiddle template: [JSFiddle](https://jsfiddle.net/nolimits4web/o2ejupu1/)

### Actual Behavior
Explain what is actually happening

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/framework7io/framework7/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.

**Comment by yash970** [comment]
![image](https://user-images.githubusercontent.com/59255648/71478754-13e43a00-27a6-11ea-90b1-6697f776768f.png)
