### ISSUE TITLE
Uncaught TypeError: Cannot set property 'f7View' of undefined

### ISSUE THREAD

**Issue by yash970** [framework7io/framework7#3459]
* Framework7 version: [e.g. 3.0.0]
* React.js version: [e.g. 16.0.0]
* Platform and Target: [e.g. iOS 11 Cordova app, or Android 8 Chrome browser]
* Live Link or JSFiddle: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_. You can start from forking the following JSFiddle template: [JSFiddle](https://jsfiddle.net/nolimits4web/vxb8oyke/)

### Actual Behavior
Explain what is actually happening

###
###[New Bitmap Image.pdf](https://github.com/framework7io/framework7/files/4002805/New.Bitmap.Image.pdf)

**Comment by yash970** [comment]
###
###[Image 3.pdf](https://github.com/framework7io/framework7/files/4002826/Image.3.pdf)

**Comment by yash970** [comment]
![Image 3](https://user-images.githubusercontent.com/59255648/71480475-1a76af80-27ae-11ea-9179-afc7c3a7c264.gif)

**Comment by yash970** [comment]
###![image](https://user-images.githubusercontent.com/59255648/71480484-2bbfbc00-27ae-11ea-8057-3f6849751581.jpg)

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/framework7io/framework7/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
