### ISSUE TITLE
The resizable grid can't be resized using a mouse / touchpad.

### ISSUE THREAD

**Issue by bible-project** [framework7io/framework7#3483]
* Framework7 version: 5.3.2 Core
* Platform and Target: Windows 10 Chrome browser, Firefox browser

### Describe the bug
The resizable grid can't be resized using a mouse / touchpad.

### To Reproduce
1. Go to https://framework7.io/docs/grid.html#examples
2. Try to resize grid using a mouse or touchpad, but not a sensor screen
4. Resize not working

### Expected behavior
Grid can be resized using a mouse / touchpad.

**Comment by shastox** [comment]
everything works

**Comment by Donchurru** [comment]
Hello.
We are having a similar problem, but it happens only since yesterday and on some computers.
For example if you go to https://framework7.io/docs/autocomplete.html#examples And try to click in one item of the "Dropdown With All Values" and it doesn't work.

But, for example, if you select In chrome the movil simulator, it works fine.

This problem only happen on some computers, it doesn't depend on the browser,  it depens on the computer.

I don't know why.

A similar thing happens here: https://framework7.io/docs/picker.html#examples If you try to change the item of a picker clicking and dragging and it doesn't work.

PD: Sorry for my English.

**Comment by shastox** [comment]
Do you have the same problems in 5.3.0?

**Comment by Donchurru** [comment]
In my project, I'm using this versions:
+-- framework7@5.1.0
+-- framework7-icons@3.0.0
+-- framework7-vue@5.1.0

But it neither works in the examples of f7.

**Comment by bible-project** [comment]
Checked everything one more time on two laptops. Both running Windows 10 (18363.592) Chrome 79.0.3945.130. The first one has touchscreen, the second one does not.

The issue is reproduced only on a laptop with a touchscreen. I can resize grid only using a touchscreen, not a touchpad.

If I turn off touchscreen in the device manager and relaunch Chrome, I can resize using a touchpad. The same thing with Firefox.

It's weird, why resizing with touchpad/mouse not working if you have a touchscreen.

**Comment by Donchurru** [comment]
@bible-project that makes sense because my laptop is an Asus ScreenPad and yesterday it received an update of the ScreenPad.

Probably it results in the problem because the screenpad can be used like a thrid screen an it is a touchscreen.

**Comment by ndikanov** [comment]
I have this issue on my laptop with a touchscreen. The modules, which use `touchstart`, `touchmove`, `touchend` are affected:
- Autocomplete
- Calendar - time picker
- Color Picker
- Grid - resizing grid
- Panels - resizing panels

I think the problem is in [touch.js:451](https://github.com/framework7io/framework7/blob/39773c245e7aa7efdc0971e25c764d9939077792/src/core/modules/touch/touch.js#L451):
``` javascript
touchEvents: {
      start: Support.touch ? 'touchstart' : (Support.pointerEvents ? 'pointerdown' : 'mousedown'),
      move: Support.touch ? 'touchmove' : (Support.pointerEvents ? 'pointermove' : 'mousemove'),
      end: Support.touch ? 'touchend' : (Support.pointerEvents ? 'pointerup' : 'mouseup'),
    },
```
