### ISSUE TITLE
data-push-state in example app doesn't work?

### ISSUE THREAD

**Issue by wysisoft** [framework7io/framework7#3484]
create blank vue project using vue ui
add framework7 0.1.1 plugin using vue ui
add data-push-state="true" to the main vue
click about link and I don't see any hash.

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/framework7io/framework7/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
