### ISSUE TITLE
Incompatible headers in Android App

### ISSUE THREAD

**Issue by lyj73231** [framework7io/framework7#3548]
在安卓app中，头部不兼容，不见了部分页面内容，如图所示：

https://mail.google.com/mail/u/0?ui=2&ik=f11260bcc8&attid=0.1&permmsgid=msg-a:r-4040298514261979637&th=1708ec71429154a7&view=fimg&sz=s0-l75-ft&attbid=ANGjdJ84rK6a2EJdONJiFHsxmQ9msYWLKEsUpnMjfO4rEmqMOoGe4AaP1XWZYDjKEqy_Gr4PbKtSVhVHXXgx9DQ_P8l8wJxKuA9k8EW9slQ-wofxQiYomh1Q1oyWZLY&disp=emb&realattid=ii_k76zlv2f0

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/framework7io/framework7/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
