### ISSUE TITLE
Scrolling broken while using Chrome "inspect device"

### ISSUE THREAD

**Issue by aetonsi** [framework7io/framework7#3643]
* Framework7 version: 5.7.5 (f7+vue+cordova)
* Platform and Target: android 9 cordova app, built on win 10 x64
* Live Link or JSFiddle: /

### Describe the bug
Scrolling / touch events seem to be broken while using chrome "inspect devices" functionality. Most of the touches are ignored.
If i start the touch over an `<f7-link>` element, scrolling almost always work.
As soon as i close the inspector, everything works again.

### To Reproduce
Build the app and install it on device (android).
"Inspect" the app via [](chrome://inspect/#devices) .
Try to scroll in the app.

### Screenshots / video
![ezgif-6-56ed903213c9](https://user-images.githubusercontent.com/18366087/82471007-6102d880-9ac6-11ea-975a-f46903dc6865.gif)

<hr>

Thank you for your time, have a nice day

**Comment by aetonsi** [comment]
Problem still present

**Comment by hacheraw** [comment]
My case is not the best one because I'm using Framework7 **v1** but I got this problem too in latest Chrome on linux

I have this problem since I started working on this project months ago. The only solution is to close Inspector.

Anyway I think this can be caused by Framework7, cordova, chrome, plug-in, a js library...
