### ISSUE TITLE
when set pushStateSeparator : '', assets on dynamic path 404 error

### ISSUE THREAD

**Issue by andriimanundin27** [framework7io/framework7#3650]
when set pushStateSeparator : '', assets on dynamic path 404 error

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/framework7io/framework7/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.

**Comment by lansulquiorra** [comment]
i have this problem too, when using empty pushStateSeparator "" on react.

my route : [
...,
  {
    path: '/product/:slug',
    asyncComponent: import('@pages/product/index')
  },
]

when i try to navigate it's work 100%, but when access from url or reload page an error occurs like this: 
<img width="537" alt="Screen Shot 2020-06-18 at 10 36 54" src="https://user-images.githubusercontent.com/15224186/84975652-29805e00-b150-11ea-8e1a-d6d41b2e4b91.png">
