### ISSUE TITLE
I have serious slowness problems. Popups, scroll, inputs.

### ISSUE THREAD

**Issue by AldeirJampier** [framework7io/framework7#3693]
I have serious slowness problems. Popups, scroll, inputs.

I'm using f7 + vue

Any solution?

**Comment by shastox** [comment]
iOS version?

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/framework7io/framework7/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.

**Comment by AldeirJampier** [comment]
> iOS version?

Android
