### ISSUE TITLE
framework7-vue The page sticks when i clike！！！！！！！！！

### ISSUE THREAD

**Issue by toosui** [framework7io/framework7#3714]
**点着点着 有时候会卡死 怎么点都点不动 什么情况下会出现？？好多这种情况了！

It gets stuck a lot ，dont Click on the framework7-vue**

**Comment by catalsdevelop** [comment]
works for me. my ua is
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36
```

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/framework7io/framework7/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
