### ISSUE TITLE
Dark theme added to Text Editor Toolbar wether autoDarkTheme is enabled or not

### ISSUE THREAD

**Issue by christopherafbjur** [framework7io/framework7#3747]
* Framework7 version: 5.7.0
* Platform and Target: iOS 14

### Describe the bug
As the title states dark theme (class theme-dark) is being added to text editor toolbar element (class text-editor-keyboard-toolbar) wether autoDarkTheme is undefined or explicitly set to true/false in the app object.

### To Reproduce
Open a text editor on iOS device with active dark mode.

### Expected behavior
The toolbar will be having the dark-theme class at all times.

### Actual Behavior
The theme-dark class is being added to the text-editor-keyboard-toolbar, not taking app setting autoDarkTheme parameter (or default value false) into consideration.

### Screenshots
-

**Comment by DAnn2012** [comment]
Following the code of the latest v5 release (but also in the code in the next v6 it is like that)

https://github.com/framework7io/framework7/blob/31f4c7065e8abe9b8b27f354de4e390a8cd584c0/src/core/components/text-editor/text-editor-class.js#L401-L405

the **theme-dark** class is added to the **text-editor-keyboard-toolbar** in these two cases:

1. If the "**.theme-dark**" CSS selector is present among the closest elements in the DOM tree (or in the current item itself)
2. _**= OR =**_ If the Device **prefersColorScheme()** method returns "**dark**" as preferred user system color scheme with **(prefers-color-scheme: dark)** media query

Otherwise, no class referring to the theme is attributed.

Therefore, currently, the **autoDarkTheme** parameter is not considered for adding the **theme-dark** class but at least one of these two cases.
