### ISSUE TITLE
Photo Browser :   onTouchMove   Error

### ISSUE THREAD

**Issue by virvnsn** [framework7io/framework7#3818]
![image](https://user-images.githubusercontent.com/44972072/106352088-8285b680-631b-11eb-8bc7-b4fca1c8c7f8.png)

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/framework7io/framework7/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
