### ISSUE TITLE
Problem with <br>

### ISSUE THREAD

**Issue by ahmedfawky** [framework7io/framework7#3858]
* Framework7 version: 6.0.14
* Platform and Target: Browser
* Live Link or JSFiddle: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_. You can start from forking the following JSFiddle template: [JSFiddle](https://jsfiddle.net/nolimits4web/o2ejupu1/)

### Describe the bug
Problem when i'm trying to use <br> html tag in <template> section
Note : this work <br />

### Actual Behavior
Explain what is actually happening

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/framework7io/framework7/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
