### ISSUE TITLE
Something w

### ISSUE THREAD

**Issue by xiaomingyu-git** [framework7io/framework7#3901]
* Framework7 version: [e.g. 3.0.0]
* React.js version: [e.g. 16.0.0]
* Platform and Target: [e.g. iOS 11 Cordova app, or Android 8 Chrome browser]
* Live Link or JSFiddle: PREFERABLY _(IF YOU WANT YOUR ISSUE TO BE RESOLVED ASAP)_. You can start from forking the following JSFiddle template: [JSFiddle](https://jsfiddle.net/nolimits4web/vxb8oyke/)

### Actual Behavior
Explain what is actually happening

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/framework7io/framework7/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.

**Comment by xiaomingyu-git** [comment]
In  smart-select with ts ,el props is required , like this .
     el: HTMLElement | CSSSelector;
    /** Link to initialized View instance which is required for Smart Select to work. By default, if not specified, it will be opened in parent View. */
    But sometimes ,it is ok to use default value.
I think  
     el?: HTMLElement | CSSSelector;
is better.

Could anyone tell me ,what is  "parent View "  in last file ?

[SearchPage.md](https://github.com/framework7io/framework7/files/6614583/SearchPage.md)

**Comment by xiaomingyu-git** [comment]
> Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/framework7io/framework7/blob/master/CONTRIBUTING.md).
> 
> Please fill the issue template correctly and:
> 
> * Clearly describe the issue including steps to reproduce when it is a bug.
> * Make sure you fill in the earliest version that you know has the issue.
> * Provide live link or JSFiddle/Codepen or website with isssue
> 
> It will save a lot of time for other contributors to check your issue and fix it.


sorry for witing it for a long time
