### ISSUE TITLE
Framework7-Vue tabview sample can't running in iOS 14

### ISSUE THREAD

**Issue by Picktarget** [framework7io/framework7#3918]
I got statusbar overlayswebview is not a function

    "dependencies": {
        "cordova-plugin-splashscreen": "6.0.0",
        "cordova-plugin-whitelist": "1.3.4",
        "cordova-plugin-statusbar": "2.4.3",
        "monaca-plugin-monaca-core": "3.3.1",
        "dom7": "^2.1.5",
        "framework7": "^5.7.11",
        "framework7-icons": "^3.0.1",
        "framework7-vue": "^5.7.11",
        "template7": "^1.4.2",
        "vue": "^2.6.12"
    },

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/framework7io/framework7/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.

> Do you want to ask a question? Are you looking for support? The [Framework7 forum](http://forum.framework7.io/) and [Stack Overflow](http://stackoverflow.com/questions/tagged/framework7) are the best places for getting support

> Please, don't use GitHub issues for questions
