### ISSUE TITLE
open in app with nothing when f7-view set browserHistory to true

### ISSUE THREAD

**Issue by AlwaysLoveme** [framework7io/framework7#3937]
* Framework7 version: latest
* Vue.js version: latest
* Platform and Target: [Android]

### Describe the bug
load pages in android device with webview, but there is show nothing on webview when "f7-view" set browserHistory to true

### Expected behavior
show pages correct
### Actual Behavior
show pages incorrect

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/framework7io/framework7/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
