### ISSUE TITLE
photo browser

### ISSUE THREAD

**Issue by lws68825** [framework7io/framework7#4009]
Hi,
I noticed photo browser did not work properly when I test the demo on the home page of framework7.io using my mobile phone. When I swipe back from photo 2 to photo 1, it always showed photo 2. Is it a bug of the photo browser?

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/framework7io/framework7/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
