### ISSUE TITLE
Routable tabs on 2nd page has a swipe back issue on IOS

### ISSUE THREAD

**Issue by XtremeBreaker** [framework7io/framework7#4152]
Hi so yeah I noticed that  while routable tabs on index main page are ok. 2nd pages have this issue swipeback issue on IOS..
https://user-images.githubusercontent.com/128444952/226510129-2f00a555-3a9d-4fef-84d6-8e41ed11a3d9.mp4

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/framework7io/framework7/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
