### ISSUE TITLE
Svelte. Framework7 popup visibility binding is broken.

### ISSUE THREAD

**Issue by ievgennaida** [framework7io/framework7#4256]
Framework 7 popup visibility on open is broken (not displayed when true and etc)

- Framework7 
    "framework7": "8.3.2",
    "framework7-svelte": "8.3.2",

- Svelte version: 4.2.12
- Platform and Target: Chrome

STR
1. Add popup.
2. Close popup on **timeout** after some button click inside of the popup.
3. Add buttons controlling visibility.
4. See that opened state and binding is desinconized after interactions.

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/framework7io/framework7/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
