### ISSUE TITLE
Svelte 4 warning "no exports condition" when framework 7 library is used.

### ISSUE THREAD

**Issue by ievgennaida** [framework7io/framework7#4257]
Warning when trying to build framework 7 with vite:

12:10:54 AM [vite-plugin-svelte] WARNING: The following packages have a svelte field in their package.json but no exports condition for svelte.

framework7-svelte@8.3.2

Please see https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition for details.

Versions:
    "svelte": "4.2.12",
    "framework7": "8.3.2",
    "framework7-svelte": "8.3.2",

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/framework7io/framework7/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
