### ISSUE TITLE
Svelte. Popup/f7Popup backdrop is not disposed onDestroy

### ISSUE THREAD

**Issue by ievgennaida** [framework7io/framework7#4258]
Framework 7 popup backdrop remains when popup is unmounted.

Framework7
"framework7": "8.3.2",
"framework7-svelte": "8.3.2",

Svelte version: 4.2.12

Platform and Target: **Chrome**

### Describe the bug

When popup was opened and component is unmounted than popup backdrop is not removed.

### To Reproduce
Display popup not in the fullscreen mode.

// Simulate component unmounted:
{#if componentVisible}

<PopUp>
<Button onClick={()=>{ componentVisible  = false } }>Remove Component</Button>
</PopUp>

{/if}

### Expected behavior

Popup is closed and unmounted with the backdrop overlay.

### Actual Behavior

Popup is closed but gray backdrop is displayed.

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/framework7io/framework7/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
