### ISSUE TITLE
MAIN VIEW CRASH AND RELOAD AGAIN BUG

### ISSUE THREAD

**Issue by beanhacker** [framework7io/framework7#4262]
Hi,
  environment:  
  "framework7": "^8.0.3";
  "framework7-vue": "^8.0.3";
   "vue": "^3.4.4",
    "vue-router": "^4.2.5",
    "vuex": "^4.1.0",
    windows: 10
  
   My F7 main view will reload when i have entered some pages, deepth >= 3, and call router.back() from current page for once, the App will reload, console log is "app mounted...", please help me. 
   The code is below: 
<template>
  <f7-app v-bind="f7params">
    
    <f7-view main url="/"></f7-view>
  </f7-app>
</template>

<script>
import routes from './router/index.js';
import { f7App, f7View } from 'framework7-vue';
export default {
  components:{
    f7App, f7View
  },
  data() {
    return {
      // Framework7 parameters that we pass to <f7-app> component
      f7params: {
        // Array with app routes
        routes,
        // App Name
        name: 'shop App'
      }
    }
  },
  mounted(){
    console.log("app mounted...");
  }
}
</script>

<style>
  #app{
    width: 100%;
    height: 100%;
    padding: 0px;
  }
</style>

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/framework7io/framework7/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.
