### ISSUE TITLE
How to stopImmediatePropagation for pageBack event?

### ISSUE THREAD

**Issue by qq286735628** [framework7io/framework7#903]
like this

``` javascript
$('.page').on('pageBack', function(evt){
  if (!condition){
    evt.stopImmediatePropagation();
  }
})
```

in some condition, i can stop `pageBack`

**Comment by nolimits4web** [comment]
If it is actual, what are you trying to achieve with this?

**Comment by qq286735628** [comment]
asking the users for confirmation to leave the page like `beforeunload` Event.

**Comment by erickfrancis** [comment]
@qq286735628 , Hello, solve the problem ? :smile:

**Comment by ZanderBrown** [comment]
@nolimits4web this could have some use cases

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
