### ISSUE TITLE
hidebar on scroll using tabs Framework 7

### ISSUE THREAD

**Issue by josieboy** [framework7io/framework7#935]
i have an animated framework7 tab with 3 items , i want to hide the navbar when each of the tab item is scrolled i only had luck hiding the navbar after scrolling the first tab item. The second and third item would never hid the navbar . how can i make this work 

Here is my jsfiddle https://jsfiddle.net/esw3fu7p/

**Comment by valnub** [comment]
I think he wants the navbar to automatically hide when scrolling down. When scrolling up, it should re-appear. Maybe we can do this for v2 of F7.

**Comment by zlatkovtv** [comment]
Hello,

I have the same problem as @josieboy . I have a navbar with a subnavbar(tabbar) on top of my page. I have 4 tabs. My objective is to hide the navbar with down-scrolling and show with up-scrolling, which will in turn, shift up the tabbar in place of the navbar. However this happens successfully only when I'm scrolling on the first tab. Its not happening on the other 3, the navbar does not hide.

Here is a link to the code for the page which contains the tabs.

https://pastebin.com/9kuywCLh

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
