### ISSUE TITLE
pushState problems in Version1.4.2 and 1.4.0

### ISSUE THREAD

**Issue by rwsbillyang** [framework7io/framework7#942]
## Problems in version 1.4.2:

1. I used swiper3.0.1(3.3.1 also same) in a page in my app, the css layout is messy, no problem  under F7 version1.4.0 ;
2. Version 1.4.2 push State problems: cannot back to home page, init code as follows:
```js
    var myApp = new Framework7({
        init: false,
       pushState: true,
    pushStateSeparator:"",
       pushStateRoot:basePath,
       pushStateOnLoad:false,
    ...
}); 
....
myApp.init();
```
If set pushStateOnLoad:true, the problem back to home gone, but at the same in home page, data loaded by ajax in pageInit callback  cannot be shown in page. If  close pushState, the problem gone.

3. Version 1.4.2  home page pageInit callback won't be called if  init code as follows:
```js
    var myApp = new Framework7({
       init: true,
       pushState: true,
    pushStateSeparator:"",
       pushStateRoot:basePath,
       pushStateOnLoad:false,
    ...
}); 
```
## Problems in Version 1.4.0

2. pageInit callback of home page will be called twice likes:
```js
var myApp = new Framework7({
       init: false,
       pushState: true,
       pushStateSeparator:"",
       pushStateRoot:basePath,
        ...
}); 
....
myApp.init();
```
2. data loaded by ajax in pageInit callback  cannot be shown in home page. If  close pushState, the problem gone.

**Comment by ZanderBrown** [comment]
@nolimits4web can you have a look at this?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
