### ISSUE TITLE
Problem with ripple effect on Android

### ISSUE THREAD

**Issue by hcw12889** [framework7io/framework7#951]
This problem doesn't exist in desktop or iOS.
Unfortunately in Android, the ripple effect is not going well.

Every time when I press a button or whatever, the ripple is only lasting for about 1 second then the effect flies away quickly, but in iOS the effect is running well.

Is it the problem cause by default long press in Android system? Or maybe I've set a wrong parameter while setting up Framework7?

Please help and thanks.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
