### ISSUE TITLE
onPageActivate event

### ISSUE THREAD

**Issue by plashenkov** [framework7io/framework7#963]
Hello!

Some sort of onPageActivate event needed.
onPageAfterAnimation event does not always trigger—for example, when parameter `reload: true` is used (or maybe in other cases).
An event that triggers distinctly and necessarily when a page activates would be good.

Or maybe I missed something?

Which method can be used now, in current version of Framework7, to handle page activate event?

**Comment by nolimits4web** [comment]
But in this case the `pageInit` and `pageBeforeInit` events will occur

**Comment by plashenkov** [comment]
I understand, yes. But the same page in a particular application in different places can be loaded with `reload: true` as well as without `reload: true`, and in the first case `pageInit` will work correctly, in the second case — no. In the second case user can go farther through the screens, the page will be removed from DOM, then he hits back, back — and pageInit will trigger even if page was not shown yet (it only was initialized again and inserted to the DOM).

(Practical example: I want to enable or disable side panel when one or another screens is shown.) 

Or, for example, now I use parameter `reload: true`, and later I may want to remove it. I must remember that I need to move my code related to page activation from pageInit to pageAfterAnimation. That may be OK for a small application to remember everyting, but if an application is large enough, it becomes hard to do that. Just some convenient event is needed. That’s my vision.

**Comment by yunusbolat** [comment]
pageCenter and pageRefresh events can be added like this. We need refresh because during refresh pageBeforeAnimation does not trigger. We can not use init because sometimes init occurs even we dont see the page.

`
function createPageCallback(callbackName) {
	var capitalized = callbackName.replace(/^./, function (match) {
		return match.toUpperCase();
	});
	myApp['onPage' + capitalized] = function (pageName, callback) {
		return myApp.onPage(callbackName, pageName, callback);
	};
}
		

var pageCallbacksNames = ('center refresh').split(' ');

for (var i = 0; i < pageCallbacksNames.length; i++) {
	myApp.pageCallbacks[pageCallbacksNames[i]] = {};
	createPageCallback(pageCallbacksNames[i]);
}


function addPageTrigger(callbackName,pageData){
	
	var capitalized = callbackName.replace(/^./, function (match) {
		return match.toUpperCase();
	});	
	
	myApp.pluginHook('page'+capitalized, pageData);
	if (myApp.params['onPage' + capitalized]) myApp.params['onPage' + capitalized](myApp, pageData);				
	myApp.triggerPageCallbacks(callbackName, pageData.name, pageData);
	$$(pageData.container).trigger('page'+capitalized, {page: pageData}); 	
}


$$(document).on('pageBeforeAnimation pageReinit pageRefresh', function (e) { 
	var pageData=e.detail.page;
	addPageTrigger('center',pageData);
});
$$(document).on('pageInit ', function(e){

	var pageData=e.detail.page
	
	var dataPageOnCenter=$$('.page-on-center').attr('data-page');

	if(dataPageOnCenter==pageData.name){
		addPageTrigger('refresh',pageData);
	}	

});

$$(document).on('pageCenter', function (e){
	var page=e.detail.page.name;
	console.log(page+' activated');
	myApp.hideIndicator();
});

$$(document).on('pageRefresh', function (e){
	var page=e.detail.page.name;
	console.log(page+' refreshed');
	myApp.hideIndicator();
});	
`

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
