### ISSUE TITLE
Community: Revive freenode IRC Channel #framework7

### ISSUE THREAD

**Issue by ionas** [framework7io/framework7#966]
What do you think?

**Comment by johnjamesjacoby** [comment]
Okay with me. I'm surprised there isn't a Slack network yet, too.

**Comment by ionas** [comment]
#johnjamesjacoby well I am there every day and so are 1-2 other peeps. Maybe we can grow this.
I am not deep into hybrid dev but Ionic seems to have a lot more traction (87 peeps in #ionic ) yet it seems to me in case you just focus on android+ios framework7 is a great choice (possibly a better one for speed and ease to get into). So I encourage you to join on IRC :)

**Comment by ionas** [comment]
Could there be a bridge-bot for Slack and Gitter in case any of that is being used.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
