### ISSUE TITLE
Calendar format in tablet (iPad)

### ISSUE THREAD

**Issue by vuphuctho** [framework7io/framework7#974]
Auto-convert to popover in tablet seems to remove the default toolbar template.

**Comment by nolimits4web** [comment]
For example?

**Comment by vuphuctho** [comment]
In framework7.js:
```
   var Calendar = function (params) {
       ...
       toolbarCloseText: 'Done',
       headerPlaceholder: 'Select date',
       header: app.params.material,
       footer: app.params.material,
       toolbarTemplate:
                    '<div class="toolbar">' +
                        '<div class="toolbar-inner">' +
                            '{{monthPicker}}' +
                            '{{yearPicker}}' +
                        '</div>' +
                    '</div>', 
        ...         
   }
```
The default popover's toolbar with close button 'Done' is overwritten with new toolbarTemplate. You can see this in [kitchen sink](http://framework7.io/kitchen-sink-ios/) for iOS.

**Comment by nolimits4web** [comment]
This is what i see when i open it as a popover:

<img width="1092" alt="ss" src="https://cloud.githubusercontent.com/assets/999588/15538493/41ea78c6-2285-11e6-9027-aac43c1ed18d.png">


Can't see anything wrong with it. Conversion to popover doesn't modify any specified templates

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
