### ISSUE TITLE
Will it be possible to apply something like in framework7?

### ISSUE THREAD

**Issue by chalchis** [framework7io/framework7#976]
Will it be possible to apply
something like in framework7
the Hamburger Menu bottom?

![tabburger-menu](https://cloud.githubusercontent.com/assets/2206648/15187872/7e381162-1768-11e6-8e58-53f4790cb02c.gif)

**Comment by Whebcraft** [comment]
try it with the picker-modal

**Comment by murliatdure** [comment]
+1

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
